/* ============================================================================
   amenti-attica.js  ·  ATTICA — the first place
   ----------------------------------------------------------------------------
   A hundred miles from the Acropolis, at 39 metres a pixel. Marathon, Salamis,
   Thermopylae, Plataea, Delphi, Corinth, Sparta and Mycenae in one frame, on
   ground measured rather than drawn.

   ── IT IS A SECOND SURFACE, NOT A ZOOM OF THE FIRST ───────────────────────
   The world map answers WHERE AT THE SCALE OF A LIFE: a soul was born at a
   city, an event happened at a place. Every one of those resolves to a
   coordinate and a year and nothing finer, and at 40 km a pixel that is the
   right instrument.

   THIS ANSWERS A DIFFERENT QUESTION. Ninety Athenian demes. Twenty-four ports.
   Twenty-three named gates in the Themistoclean wall. At world scale all of
   that is one dot; here it is a landscape, and the ground is the explanation
   rather than the backdrop.

   So it takes the screen the way the map does, on its own scene class, with
   its own projection and its own camera. It does not zoom the world map and it
   does not edit it.

   ── A MODULE, AND IT STAYS ONE ────────────────────────────────────────────
   One script tag in hall.html and NO EDIT TO amenti-map.js. It joins the
   faculty rail through AmentiMap.addFaculty, beside the globe, the glass, the
   gates and the ground.

   On 6-7 September five reasoned changes to the map file each had to be
   reverted. Every instrument built since has been a module, and not one has
   been able to take the map down. This is the fifth.

   ── WHAT IT READS ─────────────────────────────────────────────────────────
       ATTICA.jpg   8192 x 8191 · land at 30 m from Copernicus, sea at 462 m
                    from ETOPO · generated by tools/render-attica.py
       ATTICA.csv   1,746 places from Pleiades · CC BY 3.0 · a URI per row

   Both are optional in the sense that failing to load one is stated rather
   than fatal: ground without places is a chart, places without ground is a
   constellation, and either is better than a blank surface with no reason
   given.

   ── THE ONE LAW COMES WITH IT ─────────────────────────────────────────────
   A PIN AND A WASH MUST NEVER BE MISTAKEN FOR ONE ANOTHER — and here the
   distinction is not this ship's judgement. Pleiades marks its own locations
   `precise` or `rough`, where rough means THE BOUNDS WITHIN WHICH THE FEATURE
   SHOULD BE SOUGHT. Classicists arrived at the same rule independently, and it
   is carried through rather than re-derived. 1,567 pin, 179 wash.

   ── AND THE SHORELINE IS MODERN, WHICH IS A CLAIM ─────────────────────────
   Every coast in ATTICA.jpg is today's. Thermopylae's has moved six kilometres
   since 480 BC, measured on this same ground; Piraeus, Eleusis and Marathon
   are all silted harbours. The terrain is the baseline because it is complete
   and free, NOT because it is contemporary with anything drawn on it. The
   surface says so where a reader will see it.
   ========================================================================== */
(function () {
  'use strict';

  var SVGNS = 'http://www.w3.org/2000/svg';
  var RAW = 'https://raw.githubusercontent.com/ianingram/Amenti.live/main/';

  /* the box render-attica.py cut, and the projection that matches it */
  var LA0 = 36.542, LA1 = 39.425, LO0 = 21.899, LO1 = 25.556;
  var VB = 1000;                       /* square: the box is 1.0002 tall */
  var K = 1, TX = 0, TY = 0, K_MIN = 1, K_MAX = 12;

  /* ── THE REGISTER KNOWS PERIODS, NOT YEARS · measured 7 Sep ──────────────
     The first version of this surface offered year buttons — 480 BC, 430 BC,
     330 BC, AD 150 — chosen because Salamis, the plague, Alexander and
     Pausanias are what a person remembers. THE REGISTER CANNOT DISTINGUISH
     ANY OF THEM.

     Counted out of ATTICA.csv: 399 spans begin at 550 BC, 311 at 750 BC, 40 at
     330 BC; 411 end at AD 300, 151 at AD 640, 135 at 30 BC. Those are not
     events. They are the Barrington Atlas PERIOD BOUNDARIES — Archaic,
     Classical, Hellenistic, Roman, Late Antique — and Pleiades records "this
     was attested in the Classical period", which the harvest turned into 550 BC
     because a range needs a number.

     So 480 BC filtered nothing. Salamis sits inside 550-330 with everything
     else, and a button offering to find it was an interface promising a
     precision the data does not hold. THAT IS THE WASH-DRAWN-AS-A-PIN FAULT
     WEARING A DIFFERENT HAT.

     The count by century is a plateau, not a set of peaks:

         700 BC  324      AD 100  567
         500 BC  711      AD 300  582
         300 BC  692      AD 400  172
         100 BC  692      AD 600  171

     Five states. Five buttons. Each named for what the register actually
     holds, and each carrying the years so a reader can see the grain. */
  var PERIODS = [
    { k: 'all',  label: 'all of it',    a: null, b: null },
    { k: 'arch', label: 'archaic',      a: -750, b: -550, when: '750–550 BC' },
    { k: 'clas', label: 'classical',    a: -550, b: -330, when: '550–330 BC' },
    { k: 'hell', label: 'hellenistic',  a: -330, b:  -30, when: '330–30 BC' },
    { k: 'rome', label: 'roman',        a:  -30, b:  300, when: '30 BC–AD 300' },
    { k: 'late', label: 'late antique', a:  300, b:  640, when: 'AD 300–640' }
  ];

  var el = null, svg = null, view = null, open = false;
  var rows = null, loadErr = null, era = PERIODS[0];

  function proj(lat, lon) {
    return [(lon - LO0) / (LO1 - LO0) * VB,
            (LA1 - lat) / (LA1 - LA0) * VB];
  }

  function esc(s) {
    return String(s == null ? '' : s).replace(/[&<>"]/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c];
    });
  }
  function yr(y) { return y < 0 ? Math.abs(y) + ' BC' : 'AD ' + y; }

  /* ── READING THE REGISTER ───────────────────────────────────────────────
     ATTICA.csv is written by tools/harvest-attica.py and quotes any field
     holding a comma, so the parse respects quotes rather than splitting on
     every comma \u2014 the fault that broke SEATS.csv on 6 September, where 25 rows
     gained a column because a note held a comma inside single quotes. */
  function parse(text) {
    var lines = String(text).replace(/\r\n/g, '\n').split('\n');
    var cols = split(lines[0]), out = [];
    for (var i = 1; i < lines.length; i++) {
      if (!lines[i].trim()) continue;
      var c = split(lines[i]), o = {};
      for (var j = 0; j < cols.length; j++) o[cols[j]] = c[j] == null ? '' : c[j];
      o.lat = +o.lat; o.lon = +o.lon;
      o.from = o.from === '' ? null : +o.from;
      o.until = o.until === '' ? null : +o.until;
      if (!isNaN(o.lat) && !isNaN(o.lon)) out.push(o);
    }
    return out;
  }
  function split(line) {
    var c = [], cur = '', q = false;
    for (var i = 0; i < line.length; i++) {
      var ch = line[i];
      if (ch === '"') { q = !q; continue; }
      if (ch === ',' && !q) { c.push(cur); cur = ''; continue; }
      cur += ch;
    }
    c.push(cur);
    return c;
  }

  function style() {
    if (document.getElementById('at-css')) { return; }
    var s = document.createElement('style');
    s.id = 'at-css';
    s.textContent = [
      '#amenti-attica{position:fixed;inset:0;z-index:3;opacity:0;visibility:hidden;',
      '  pointer-events:none;transition:opacity .45s ease .15s,visibility .45s;',
      '  font:400 13.5px/1.55 ui-monospace,Menlo,Consolas,monospace;color:#b8c4d8;',
      '  background:#05080e}',
      'body.scene-attica #amenti-attica{opacity:1;visibility:visible;pointer-events:auto}',
      /* the hall stands down, on the same terms the map already uses */
      'body.scene-attica #hall-main,body.scene-attica .hall-chrome,',
      'body.scene-attica header,body.scene-attica footer,',
      'body.scene-attica #amenti-handover,body.scene-attica #scene-hint{',
      '  opacity:0;visibility:hidden;pointer-events:none;transition:opacity .45s ease}',
      '#amenti-attica .at-wrap{position:absolute;inset:0;display:flex;',
      '  flex-direction:column;padding:22px 250px 18px 26px;gap:0}',
      '#amenti-attica svg{flex:1 1 auto;min-height:0;width:100%;cursor:grab}',
      '#amenti-attica svg.at-drag{cursor:grabbing}',
      '#amenti-attica .at-ground{pointer-events:none}',
      /* A PIN. Small, hard, bright \u2014 the map's own value, so a reader crossing
         between the two surfaces reads the same mark. */
      '#amenti-attica .at-pin{fill:#5fd0e8;fill-opacity:.85;stroke:#081018;',
      '  stroke-width:.35;vector-effect:non-scaling-stroke;cursor:pointer}',
      '#amenti-attica .at-pin:hover{fill:#a9edff;fill-opacity:1}',
      /* ── UNDATED IS NOT THE SAME CLAIM AS ATTESTED HERE ──────────────────
         705 of 1,746 places carry no span. They are drawn in every period,
         because Pleiades not knowing when is not the place not existing — but
         drawing them at full strength beside a place the register places IN
         this period would make the two look alike. Dimmer, and the count is
         stated. The same distinction as pin and wash, in a second dimension. */
      '#amenti-attica .at-undated .at-pin{fill:#7d8ea6;fill-opacity:.45}',
      '#amenti-attica .at-undated .at-name{opacity:.55}',
      /* A WASH. Soft, edgeless, never a point. Pleiades called it rough. */
      '#amenti-attica .at-wash{fill:#4a6c8f;fill-opacity:.14;stroke:none;',
      '  cursor:default}',
      '#amenti-attica .at-wash:hover{fill-opacity:.28}',
      '#amenti-attica .at-name{fill:#c3d3e6;text-anchor:middle;pointer-events:none;',
      '  opacity:0;paint-order:stroke;stroke:#05080e;stroke-linejoin:round;',
      '  transition:opacity .3s ease}',
      '#amenti-attica .at-named .at-name{opacity:.92}',
      '#amenti-attica .at-head{display:flex;justify-content:space-between;',
      '  align-items:baseline;gap:20px;margin-bottom:10px;flex:0 0 auto}',
      '#amenti-attica .at-title{color:#8fa2ba;font-size:13px}',
      '#amenti-attica .at-note{color:#6f8098;font-size:11.5px;margin-top:10px;',
      '  flex:0 0 auto;max-width:70ch;line-height:1.5}',
      '#amenti-attica .at-warn{color:#c99a4e}',
      '#amenti-attica .at-read{color:#f0f5fb;font-size:22px;letter-spacing:.01em;',
      '  font-variant-numeric:tabular-nums;white-space:nowrap}',
      '#amenti-attica .at-list{position:absolute;right:0;top:60px;bottom:90px;',
      '  width:232px;padding:12px 24px 12px 12px;overflow-y:auto;text-align:right;',
      '  background:linear-gradient(270deg,rgba(5,8,14,.94),rgba(5,8,14,0));',
      '  border-left:1px solid rgba(43,58,80,.5);scrollbar-width:thin}',
      '#amenti-attica .at-li{font-size:12px;line-height:1.5;color:#9fb1c7;',
      '  white-space:nowrap;overflow:hidden;text-overflow:ellipsis;cursor:default}',
      '#amenti-attica .at-li:hover{color:#eaf6ff}',
      '#amenti-attica .at-li span{color:#5d6e84;font-size:10.5px}',
      '#amenti-attica .at-ctl{position:absolute;left:26px;bottom:18px;z-index:6;',
      '  display:flex;gap:10px;align-items:center}',
      '#amenti-attica button{background:transparent;color:#8fa2ba;font:inherit;',
      '  font-size:11.5px;border:1px solid #23303f;border-radius:3px;',
      '  padding:5px 10px;cursor:pointer;letter-spacing:.05em}',
      '#amenti-attica button:hover{color:#c3d3e6;border-color:#33637a}',
      '#amenti-attica button[aria-pressed="true"]{color:#0a1018;background:#8fa8c4}',
      '#amenti-attica .at-hit{position:fixed;pointer-events:none;z-index:9;',
      '  background:rgba(8,12,20,.95);border:1px solid #2b3a50;border-radius:3px;',
      '  padding:7px 10px;font-size:11.5px;color:#dbe4f0;max-width:38ch;',
      '  opacity:0;transition:opacity .12s;white-space:pre-line}'
    ].join('\n');
    document.head.appendChild(s);
  }

  function mount() {
    if (el) { return el; }
    style();
    el = document.createElement('div');
    el.id = 'amenti-attica';
    el.innerHTML =
      '<div class="at-wrap">' +
        '<div class="at-head">' +
          '<div class="at-title">Attica \u00b7 a hundred miles from the Acropolis</div>' +
          '<div class="at-read"></div>' +
        '</div>' +
        '<svg viewBox="0 0 ' + VB + ' ' + VB + '" preserveAspectRatio="xMidYMid meet">' +
          '<g class="at-view">' +
            '<image class="at-ground" x="0" y="0" width="' + VB + '" height="' + VB + '" ' +
              'preserveAspectRatio="none"></image>' +
            '<g class="at-washes"></g><g class="at-pins"></g>' +
          '</g>' +
        '</svg>' +
        '<div class="at-note"></div>' +
      '</div>' +
      '<div class="at-list"></div>' +
      '<div class="at-ctl">' +
        PERIODS.map(function (p) {
          return '<button type="button" data-p="' + p.k + '"' +
                 (p.k === 'all' ? ' aria-pressed="true"' : '') +
                 (p.when ? ' title="' + p.when + '"' : '') + '>' + p.label + '</button>';
        }).join('') +
        '<button type="button" data-z="out">\u2212</button>' +
        '<button type="button" data-z="in">+</button>' +
        '<button type="button" data-z="fit">fit</button>' +
      '</div>' +
      '<div class="at-hit"></div>';
    document.body.appendChild(el);
    svg = el.querySelector('svg');
    view = el.querySelector('.at-view');
    wire();
    return el;
  }

  /* ── WHAT IS SHOWN AT A YEAR ────────────────────────────────────────────
     A place is drawn while the year sits inside its span. WITH `hi` NULL
     EVERYTHING IS DRAWN AND THE READOUT SAYS SO \u2014 1,746 at once is a smear,
     and a reader should be told that is what they are looking at rather than
     left to conclude the ground was that crowded.

     AND A PLACE WITH NO SPAN IS ALWAYS DRAWN. 705 of these carry no date,
     which is Pleiades not knowing rather than the place not existing. Hiding
     them at every year would be inventing an absence. */
  /* ── A PERIOD OVERLAPS A SPAN; A YEAR SAT INSIDE ONE ────────────────────
     The test is overlap, not containment. A place attested 550 BC to AD 300
     belongs to the Classical, Hellenistic AND Roman periods, and asking
     whether one year falls inside it would answer a question the register was
     never posed.

     AND A PLACE WITH NO SPAN IS ALWAYS DRAWN. 705 of 1,746 carry no date,
     which is Pleiades not knowing rather than the place not existing. Hiding
     them in every period would invent an absence. */
  function alive(r) {
    if (era.a === null) { return true; }
    if (r.from === null && r.until === null) { return true; }
    if (r.until !== null && r.until < era.a) { return false; }
    if (r.from !== null && r.from > era.b) { return false; }
    return true;
  }

  function draw() {
    if (!open || !rows) { return; }
    view.setAttribute('transform',
      'translate(' + TX.toFixed(2) + ' ' + TY.toFixed(2) + ') scale(' + K.toFixed(4) + ')');
    var iv = 1 / K;
    var shown = rows.filter(alive);
    var pins = shown.filter(function (r) { return r.tier === 'pin'; });
    var wash = shown.filter(function (r) { return r.tier !== 'pin'; });

    /* washes first, and they are rectangles about their point because
       ATTICA.csv carries a representative coordinate rather than the bounding
       box. THAT IS A COMPROMISE AND IT IS STATED: the true extent is in
       Pleiades' bounding_box_wkt and is not harvested yet, so this draws a
       fixed soft area meaning "somewhere about here" rather than a false one
       meaning "exactly this rectangle". */
    var wh = '';
    wash.forEach(function (r) {
      var p = proj(r.lat, r.lon), a = 9 * iv;
      wh += '<rect class="at-wash" x="' + (p[0] - a).toFixed(2) + '" y="' + (p[1] - a).toFixed(2) +
            '" width="' + (a * 2).toFixed(2) + '" height="' + (a * 2).toFixed(2) +
            '" rx="' + (3 * iv).toFixed(2) + '" data-k="' + esc(r.key) + '"/>';
    });
    el.querySelector('.at-washes').innerHTML = wh;

    /* ── THE MARK HOLDS ITS SIZE AND SO DOES ITS OUTLINE ─────────────────
       Both divided by K, together. On 6 September the type was corrected and
       the outline was not, and at x14 a 0.23 px letter sat inside a 0.91 px
       stroke: every name on the world map drew as a black lozenge. The pair
       is one thing and moves as one. */
    var ph = '', placed = [], named = 0, dropped = 0, undated = 0;
    pins.sort(function (a, b) { return (+a.km) - (+b.km); });
    pins.forEach(function (r) {
      var p = proj(r.lat, r.lon);
      var fit = true, w = (r.name || '').length * 1.6 * iv;
      for (var i = 0; i < placed.length; i++) {
        if (Math.abs(p[0] - placed[i][0]) < (w + placed[i][2]) &&
            Math.abs(p[1] - placed[i][1]) < 7 * iv) { fit = false; break; }
      }
      if (fit && K >= 1.8) { placed.push([p[0], p[1], w]); named++; } else { fit = false; dropped++; }
      var und = (r.from === null && r.until === null);
      if (und) { undated++; }
      ph += '<g class="at-seat' + (fit ? ' at-named' : '') +
            (und ? ' at-undated' : '') + '">' +
            '<circle class="at-pin" cx="' + p[0].toFixed(2) + '" cy="' + p[1].toFixed(2) +
            '" r="' + (1.5 * iv).toFixed(2) + '" data-k="' + esc(r.key) + '"/>' +
            (fit ? '<text class="at-name" x="' + p[0].toFixed(2) + '" y="' +
                   (p[1] - 3.4 * iv).toFixed(2) + '" style="font-size:' + (5 * iv).toFixed(3) +
                   'px;stroke-width:' + (1.5 * iv).toFixed(3) + 'px">' +
                   esc(r.name) + '</text>' : '') +
            '</g>';
    });
    el.querySelector('.at-pins').innerHTML = ph;

    el.querySelector('.at-read').textContent =
      era.a === null ? 'the whole register' : era.label + '  \u00b7  ' + era.when;
    el.querySelector('.at-note').innerHTML =
      shown.length + ' of ' + rows.length + ' places \u00b7 ' + pins.length + ' pinned \u00b7 ' +
      wash.length + ' somewhere in an area \u00b7 ' + named + ' named' +
      (dropped ? ', ' + dropped + ' with no room \u2014 zoom in' : '') +
      (undated ? ' \u00b7 <b>' + undated + ' undated</b>, drawn dim in every period because ' +
                 'Pleiades not knowing WHEN is not the place not existing' : '') +
      (era.a === null
        ? ' \u00b7 <b>all of it at once, which is a smear</b> \u2014 pick a period'
        : ' \u00b7 <b>the register knows five periods, not years</b> \u2014 a place ' +
          'attested \u201cClassical\u201d is dated 550\u2013330 BC because a range needs a ' +
          'number, and most spans cross every period, so this filters less than ' +
          'it looks like it should') +
      '<br>Places from Pleiades (CC BY 3.0). Land at 30 m from Copernicus, sea at ' +
      '462 m from ETOPO. <span class="at-warn">Every shoreline here is TODAY\u2019S \u2014 ' +
      'Thermopylae\u2019s has moved six kilometres since 480 BC, and Piraeus, Eleusis ' +
      'and Marathon are silted harbours.</span>';

    var lb = el.querySelector('.at-list');
    lb.innerHTML = pins.slice(0, 90).map(function (r) {
      return '<div class="at-li" data-k="' + esc(r.key) + '">' + esc(r.name) +
             ' <span>' + (r.km) + ' km</span></div>';
    }).join('') || '<div class="at-li">nothing in this year</div>';
  }

  function wire() {
    var hit = el.querySelector('.at-hit');
    el.addEventListener('pointerover', function (e) {
      var n = e.target.closest ? e.target.closest('[data-k]') : null;
      if (!n) { hit.style.opacity = 0; return; }
      var r = rows && rows.filter(function (x) { return x.key === n.getAttribute('data-k'); })[0];
      if (!r) { return; }
      hit.textContent = r.name + '\n' + (r.kind || '') +
        '\n' + (r.tier === 'pin' ? 'a position' : 'somewhere in this area') +
        (r.from !== null || r.until !== null
          ? '\nattested ' + (r.from !== null ? yr(r.from) : '?') + ' to ' +
            (r.until !== null ? yr(r.until) : '?')
          : '\nno date in the register') +
        '\n' + r.km + ' km from the Acropolis';
      hit.style.opacity = 1;
    });
    el.addEventListener('pointermove', function (e) {
      hit.style.left = (e.clientX + 14) + 'px';
      hit.style.top = (e.clientY + 14) + 'px';
    });

    el.querySelectorAll('.at-ctl button').forEach(function (b) {
      b.addEventListener('click', function (ev) {
        ev.stopPropagation();
        var pk = b.getAttribute('data-p'), z = b.getAttribute('data-z');
        if (pk !== null) {
          era = PERIODS.filter(function (p) { return p.k === pk; })[0] || PERIODS[0];
          el.querySelectorAll('.at-ctl button[data-p]').forEach(function (o) {
            o.setAttribute('aria-pressed', o === b ? 'true' : 'false');
          });
        } else if (z === 'fit') {
          K = 1; TX = 0; TY = 0;
        } else {
          zoom(z === 'in' ? 1.5 : 1 / 1.5);
        }
        draw();
      });
    });

    function zoom(f, cx, cy) {
      var r = svg.getBoundingClientRect();
      if (!r.width) { return; }
      var mx = cx == null ? VB / 2 : (cx - r.left) / r.width * VB;
      var my = cy == null ? VB / 2 : (cy - r.top) / r.height * VB;
      var wx = (mx - TX) / K, wy = (my - TY) / K;
      var k = Math.max(K_MIN, Math.min(K_MAX, K * f));
      if (k === K) { return; }
      K = k; TX = mx - wx * K; TY = my - wy * K;
      clamp();
    }
    function clamp() {
      var m = VB - VB * K;
      TX = Math.min(0, Math.max(m, TX));
      TY = Math.min(0, Math.max(m, TY));
    }
    el.addEventListener('wheel', function (e) {
      e.preventDefault();
      zoom(e.deltaY > 0 ? 0.88 : 1.14, e.clientX, e.clientY);
      draw();
    }, { passive: false });

    var pan = false, px = 0, py = 0;
    el.addEventListener('pointerdown', function (e) {
      if (e.target.closest && e.target.closest('.at-ctl,.at-list')) { return; }
      pan = true; px = e.clientX; py = e.clientY;
      svg.classList.add('at-drag');
    });
    el.addEventListener('pointermove', function (e) {
      if (!pan) { return; }
      var r = svg.getBoundingClientRect();
      TX += (e.clientX - px) / r.width * VB;
      TY += (e.clientY - py) / r.height * VB;
      px = e.clientX; py = e.clientY;
      clamp(); draw();
    });
    ['pointerup', 'pointercancel'].forEach(function (t) {
      el.addEventListener(t, function () { pan = false; svg.classList.remove('at-drag'); });
    });
    el.addEventListener('dblclick', function () { K = 1; TX = 0; TY = 0; draw(); });
    ['click', 'pointerdown'].forEach(function (t) {
      el.addEventListener(t, function (e) { e.stopPropagation(); });
    });
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape' && document.body.classList.contains('scene-attica')) {
        e.stopPropagation();
        hide();
        if (window.AmentiMap && window.AmentiMap.syncRail) { window.AmentiMap.syncRail(); }
      }
    }, true);
  }

  function show() {
    mount();
    /* the two instruments never share the screen \u2014 the map's own rule, kept */
    document.body.classList.remove('scene-bare', 'scene-map');
    document.body.classList.add('scene-attica');
    open = true;

    var img = el.querySelector('.at-ground');
    if (!img.getAttribute('href')) {
      img.addEventListener('error', function () {
        el.querySelector('.at-note').innerHTML =
          '<span class="at-warn">ATTICA.jpg did not load \u2014 the places are drawn on ' +
          'nothing. That is a chart without ground, which is what this was before ' +
          'the ground existed. Nothing is drawn in its place.</span>';
      });
      img.setAttribute('href', RAW + 'ATTICA.jpg');
    }
    if (rows === null && loadErr === null) {
      fetch(RAW + 'ATTICA.csv?_=' + Date.now())
        .then(function (r) { if (!r.ok) { throw new Error('HTTP ' + r.status); } return r.text(); })
        .then(function (t) { rows = parse(t); draw(); })
        .catch(function (e) {
          loadErr = e.message;
          el.querySelector('.at-note').innerHTML =
            '<span class="at-warn">ATTICA.csv did not load (' + esc(e.message) +
            '). The ground is drawn and nothing is on it \u2014 which is the register ' +
            'missing, not the places being absent.</span>';
        });
    }
    draw();
    return true;
  }

  function hide() {
    open = false;
    document.body.classList.remove('scene-attica');
  }
  function toggle() { return open ? (hide(), false) : show(); }

  /* an olive leaf and a coast \u2014 a place, not a world */
  var ICON =
    '<svg viewBox="0 0 24 24" aria-hidden="true">' +
    '<path d="M4 17c4-1 7-4 9-8"/><path d="M13 9c2 0 4 1 5 3"/>' +
    '<path d="M3 21h18"/></svg>';

  function join() {
    if (!window.AmentiMap || !window.AmentiMap.addFaculty) { return false; }
    window.AmentiMap.addFaculty('fac-attica', 'attica', ICON, toggle,
                                function () { return open; });
    return true;
  }
  function arrive(n) {
    if (join()) { return; }
    if ((n || 0) > 40) {
      console.log('ATTICA did not join the rail \u2014 AmentiMap.addFaculty was never ' +
                  'exported. amenti-attica.js needs amenti-map.js loaded first.');
      return;
    }
    setTimeout(function () { arrive((n || 0) + 1); }, 250);
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', function () { arrive(0); });
  } else {
    arrive(0);
  }

  window.AmentiAttica = {
    show: show, hide: hide, toggle: toggle,
    isOpen: function () { return open; },
    /* the periods by key: all arch clas hell rome late */
    period: function (k) {
      era = PERIODS.filter(function (p) { return p.k === k; })[0] || PERIODS[0];
      draw();
      return { key: era.k, from: era.a, until: era.b };
    },
    periods: function () { return PERIODS.map(function (p) { return p.k; }); },
    count: function () {
      return rows ? { places: rows.length, shown: rows.filter(alive).length,
                      pin: rows.filter(function (r) { return r.tier === 'pin'; }).length }
                  : (loadErr ? { error: loadErr } : null);
    }
  };
})();
