/* ============================================================================
   amenti-attica.js  ·  ATTICA — the first place
   ----------------------------------------------------------------------------
   A hundred miles from the Acropolis, at 39 metres a pixel. Marathon, Salamis,
   Thermopylae, Plataea, Delphi, Corinth, Sparta and Mycenae in one frame, on
   ground measured rather than drawn.

   ── IT IS A SECOND SURFACE, NOT A ZOOM OF THE FIRST ───────────────────────
   The world map answers WHERE AT THE SCALE OF A LIFE: a soul was born at a
   city, an event happened at a place. Every one of those resolves to a
   coordinate and a year and nothing finer, and at 40 km a pixel that is the
   right instrument.

   THIS ANSWERS A DIFFERENT QUESTION. Ninety Athenian demes. Twenty-four ports.
   Twenty-three named gates in the Themistoclean wall. At world scale all of
   that is one dot; here it is a landscape, and the ground is the explanation
   rather than the backdrop.

   So it takes the screen the way the map does, on its own scene class, with
   its own projection and its own camera. It does not zoom the world map and it
   does not edit it.

   ── A MODULE, AND IT STAYS ONE ────────────────────────────────────────────
   One script tag in hall.html and NO EDIT TO amenti-map.js. It joins the
   faculty rail through AmentiMap.addFaculty, beside the globe, the glass, the
   gates and the ground.

   On 6-7 September five reasoned changes to the map file each had to be
   reverted. Every instrument built since has been a module, and not one has
   been able to take the map down. This is the fifth.

   ── WHAT IT READS ─────────────────────────────────────────────────────────
       ATTICA.jpg   8192 x 8191 · land at 30 m from Copernicus, sea at 462 m
                    from ETOPO · generated by tools/render-attica.py
       ATTICA.csv   1,746 places from Pleiades · CC BY 3.0 · a URI per row

   Both are optional in the sense that failing to load one is stated rather
   than fatal: ground without places is a chart, places without ground is a
   constellation, and either is better than a blank surface with no reason
   given.

   ── THE ONE LAW COMES WITH IT ─────────────────────────────────────────────
   A PIN AND A WASH MUST NEVER BE MISTAKEN FOR ONE ANOTHER — and here the
   distinction is not this ship's judgement. Pleiades marks its own locations
   `precise` or `rough`, where rough means THE BOUNDS WITHIN WHICH THE FEATURE
   SHOULD BE SOUGHT. Classicists arrived at the same rule independently, and it
   is carried through rather than re-derived. 1,567 pin, 179 wash.

   ── AND THE SHORELINE IS MODERN, WHICH IS A CLAIM ─────────────────────────
   Every coast in ATTICA.jpg is today's. Thermopylae's has moved six kilometres
   since 480 BC, measured on this same ground; Piraeus, Eleusis and Marathon
   are all silted harbours. The terrain is the baseline because it is complete
   and free, NOT because it is contemporary with anything drawn on it. The
   surface says so where a reader will see it.
   ========================================================================== */
(function () {
  'use strict';

  var SVGNS = 'http://www.w3.org/2000/svg';
  var RAW = 'https://raw.githubusercontent.com/ianingram/Amenti.live/main/';

  /* the box render-attica.py cut, and the projection that matches it */
  var LA0 = 36.542, LA1 = 39.425, LO0 = 21.899, LO1 = 25.556;
  var VB = 1000;                       /* square: the box is 1.0002 tall */
  var K = 1, TX = 0, TY = 0, K_MIN = 1, K_MAX = 12;

  /* ── THE REGISTER KNOWS PERIODS, NOT YEARS · measured 7 Sep ──────────────
     The first version of this surface offered year buttons — 480 BC, 430 BC,
     330 BC, AD 150 — chosen because Salamis, the plague, Alexander and
     Pausanias are what a person remembers. THE REGISTER CANNOT DISTINGUISH
     ANY OF THEM.

     Counted out of ATTICA.csv: 399 spans begin at 550 BC, 311 at 750 BC, 40 at
     330 BC; 411 end at AD 300, 151 at AD 640, 135 at 30 BC. Those are not
     events. They are the Barrington Atlas PERIOD BOUNDARIES — Archaic,
     Classical, Hellenistic, Roman, Late Antique — and Pleiades records "this
     was attested in the Classical period", which the harvest turned into 550 BC
     because a range needs a number.

     So 480 BC filtered nothing. Salamis sits inside 550-330 with everything
     else, and a button offering to find it was an interface promising a
     precision the data does not hold. THAT IS THE WASH-DRAWN-AS-A-PIN FAULT
     WEARING A DIFFERENT HAT.

     The count by century is a plateau, not a set of peaks:

         700 BC  324      AD 100  567
         500 BC  711      AD 300  582
         300 BC  692      AD 400  172
         100 BC  692      AD 600  171

     Five states. Five buttons. Each named for what the register actually
     holds, and each carrying the years so a reader can see the grain. */
  var PERIODS = [
    { k: 'all',  label: 'all of it',    a: null, b: null },
    { k: 'arch', label: 'archaic',      a: -750, b: -550, when: '750–550 BC' },
    { k: 'clas', label: 'classical',    a: -550, b: -330, when: '550–330 BC' },
    { k: 'hell', label: 'hellenistic',  a: -330, b:  -30, when: '330–30 BC' },
    { k: 'rome', label: 'roman',        a:  -30, b:  300, when: '30 BC–AD 300' },
    { k: 'late', label: 'late antique', a:  300, b:  640, when: 'AD 300–640' }
  ];

  /* ── WHAT THE CORPUS NAMES · optional ────────────────────────────────────
     ATTICA-MENTIONS.csv is the join between this register and the reading
     rooms: 603 texts, 35.9 M characters, matched against 5,615 attested name
     forms. 152 of 1,746 places are named by something; 85 by more than one.

     IT IS A DIFFERENT CLAIM FROM A COORDINATE. The atlas says the Dipylon Gate
     was at 37.979N 23.718E. The corpus says people kept writing about it. A
     place with both is corroborated; a place with only the first is recorded;
     and 1,594 have only the first, which is a finding rather than an absence —
     either the library has a gap or no author cared to name a farmstead.

     Optional, and its absence is stated rather than fatal. Without it every
     place still draws; nothing is silently downgraded for want of a file. */
  var mentions = null, mentionsErr = null;

  /* ── WHAT HAPPENED HERE · optional ──────────────────────────────────────
     ATTICA-EVENTS.csv is authored. The world register holds nine events inside
     this box and SEVEN OF THEM SIT ON ONE COORDINATE — the Acropolis —
     including Plato founding the Academy, which is a mile outside the walls.
     Correct at 40 km a pixel and a lie at 39 metres.

     Each row carries `at`, a key into ATTICA.csv, so an event stands on a
     place the gazetteer holds rather than at a typed coordinate. Where no such
     place exists — a sea-fight in open water — the coordinate is authored and
     `at` is empty, which is how the file says so. */
  var events = null, eventsErr = null;

  /* ── TWO CLOCKS, BECAUSE THE TWO REGISTERS HAVE TWO GRAINS ──────────────
     The obvious thing is one scrubber moving everything. IT CANNOT BE DONE
     HONESTLY HERE, and the reason is worth stating where the next person will
     find it.

     A PLACE IN ATTICA.csv IS DATED TO A PERIOD, NOT A YEAR. Pleiades records
     "attested in the Classical period" and the harvest turns that into
     550–330 BC because a range needs a number. Measured: 399 spans begin at
     exactly 550 BC, 311 at 750 BC, 411 end at AD 300. So scrubbing from 480 to
     404 changes NOTHING among the places — every Classical entry is dated
     identically — and an animation of them would be a moving picture of a
     register that is standing still.

     AN EVENT HAS A YEAR. 490, 480, 431, 404. That is a real clock and it can
     be scrubbed.

     So the periods drive the places and the year drives the events, and the
     surface says so rather than letting a reader assume one control moves
     everything. A SURFACE WITH TWO CLOCKS IS HONEST WHERE ONE WOULD BE A LIE. */
  var scrub = null;        /* the year, or null for the whole period */
  var FADE = 40;           /* years either side that an event still glows */

  var el = null, svg = null, view = null, open = false;
  var rows = null, loadErr = null, era = PERIODS[0];

  /* ── NINE MARKS FOR A HUNDRED AND EIGHT KINDS ─────────────────────────────
     ATTICA.csv holds 108 distinct place types and drew every one as the same
     cyan dot — which told a reader that a temple, a silver mine and a ship
     harbour are the same kind of fact. They are not.

     The kinds are grouped by WHAT A READER WOULD ASK ABOUT THEM, not by
     Pleiades' vocabulary, and each mark is drawable in a few strokes at three
     pixels because that is the size it will usually be:

         settled   570   a filled dot — the default, and the map's own pin
         ground    328   a peak stroke, matching the world map's summits
         sacred    268   a gable: temple, sanctuary, shrine, acropolis
         defence   168   a crenellation: fort, tower, wall, gate
         built     113   an open square, as the world map draws a site
         worked     81   crossed strokes: mine, quarry, kiln
         games      50   an oval, the shape of the track itself
         buried     47   a stele, upright
         harbour    31   a crescent, the shape of a bay
         other      90   region, province, map label — no mark to make

     GOLD IS NOT SPENT HERE and none of these borrows the world map's ember,
     which is an event, or its amber diamond, which is the sky. */
  var MARKS = [
    ['harbour', /\bport\b|harbor|harbour|limen|mole|quay/],
    ['games',   /stadi|gymnas|palaestra|palaistra|hippodrom|theatre|theater|odeon|odeum/],
    ['sacred',  /sanctuar|shrine|acropolis|temple|altar|oracle|temenos/],
    ['defence', /\bfort|tower|wall|gate|castle|citadel|rampart/],
    ['worked',  /\bmine\b|quarry|kiln|workshop|factory/],
    ['buried',  /tomb|necropolis|cemeter|tumulus|catacomb|grave|mausoleum/],
    ['built',   /stoa|basilica|church|building|architectural|monument|bath|villa|house|library|bridge|aqueduct|fountain/],
    ['ground',  /mountain|hill|peak|cape|promontor|island|river|spring|lake|plain|valley|pass|cave|water/],
    ['settled', /settlement|deme|village|town|city|station|people/]
  ];
  function markOf(kind) {
    var k = String(kind || '').toLowerCase();
    for (var i = 0; i < MARKS.length; i++) {
      if (MARKS[i][1].test(k)) { return MARKS[i][0]; }
    }
    return 'other';
  }

  /* each returns a path `d` about the origin, at radius a */
  function shape(m, a) {
    var f = function (v) { return v.toFixed(2); };
    if (m === 'sacred') {                 /* a gable */
      return 'M' + f(-a) + ' ' + f(a * .6) + 'L0 ' + f(-a) + 'L' + f(a) + ' ' + f(a * .6);
    }
    if (m === 'defence') {                /* a crenellation */
      return 'M' + f(-a) + ' ' + f(a) + 'V' + f(-a * .3) + 'h' + f(a * .7) + 'V' + f(-a) +
             'h' + f(a * .6) + 'V' + f(-a * .3) + 'H' + f(a) + 'V' + f(a);
    }
    if (m === 'harbour') {                /* a bay, opening seaward */
      return 'M' + f(-a) + ' ' + f(-a * .5) + 'A' + f(a) + ' ' + f(a) + ' 0 0 0 ' +
             f(a) + ' ' + f(-a * .5);
    }
    if (m === 'worked') {                 /* crossed strokes */
      return 'M' + f(-a) + ' ' + f(-a) + 'L' + f(a) + ' ' + f(a) +
             'M' + f(-a) + ' ' + f(a) + 'L' + f(a) + ' ' + f(-a);
    }
    if (m === 'buried') {                 /* a stele */
      return 'M0 ' + f(a) + 'V' + f(-a) + 'M' + f(-a * .55) + ' ' + f(-a) + 'h' + f(a * 1.1);
    }
    if (m === 'built') {                  /* an open square */
      return 'M' + f(-a) + ' ' + f(-a) + 'h' + f(a * 2) + 'v' + f(a * 2) + 'h' + f(-a * 2) + 'Z';
    }
    if (m === 'ground') {                 /* a summit, as the world map draws one */
      return 'M' + f(-a) + ' ' + f(a * .7) + 'L0 ' + f(-a) + 'L' + f(a) + ' ' + f(a * .7);
    }
    if (m === 'games') { return null; }   /* an oval — drawn as <ellipse> */
    return null;                          /* settled and other — a dot */
  }

  function proj(lat, lon) {
    return [(lon - LO0) / (LO1 - LO0) * VB,
            (LA1 - lat) / (LA1 - LA0) * VB];
  }

  function esc(s) {
    return String(s == null ? '' : s).replace(/[&<>"]/g, function (c) {
      return { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c];
    });
  }
  function yr(y) { return y < 0 ? Math.abs(y) + ' BC' : 'AD ' + y; }

  /* ── READING THE REGISTER ───────────────────────────────────────────────
     ATTICA.csv is written by tools/harvest-attica.py and quotes any field
     holding a comma, so the parse respects quotes rather than splitting on
     every comma \u2014 the fault that broke SEATS.csv on 6 September, where 25 rows
     gained a column because a note held a comma inside single quotes. */
  function parse(text) {
    var lines = String(text).replace(/\r\n/g, '\n').split('\n');
    var cols = split(lines[0]), out = [];
    for (var i = 1; i < lines.length; i++) {
      if (!lines[i].trim()) continue;
      var c = split(lines[i]), o = {};
      for (var j = 0; j < cols.length; j++) o[cols[j]] = c[j] == null ? '' : c[j];
      o.lat = +o.lat; o.lon = +o.lon;
      o.from = o.from === '' ? null : +o.from;
      o.until = o.until === '' ? null : +o.until;
      if (!isNaN(o.lat) && !isNaN(o.lon)) out.push(o);
    }
    return out;
  }
  function split(line) {
    var c = [], cur = '', q = false;
    for (var i = 0; i < line.length; i++) {
      var ch = line[i];
      if (ch === '"') { q = !q; continue; }
      if (ch === ',' && !q) { c.push(cur); cur = ''; continue; }
      cur += ch;
    }
    c.push(cur);
    return c;
  }

  function style() {
    if (document.getElementById('at-css')) { return; }
    var s = document.createElement('style');
    s.id = 'at-css';
    s.textContent = [
      '#amenti-attica{position:fixed;inset:0;z-index:3;opacity:0;visibility:hidden;',
      '  pointer-events:none;transition:opacity .45s ease .15s,visibility .45s;',
      '  font:400 13.5px/1.55 ui-monospace,Menlo,Consolas,monospace;color:#b8c4d8;',
      '  background:#05080e}',
      'body.scene-attica #amenti-attica{opacity:1;visibility:visible;pointer-events:auto}',
      /* the hall stands down, on the same terms the map already uses */
      'body.scene-attica #hall-main,body.scene-attica .hall-chrome,',
      'body.scene-attica header,body.scene-attica footer,',
      'body.scene-attica #amenti-handover,body.scene-attica #scene-hint{',
      '  opacity:0;visibility:hidden;pointer-events:none;transition:opacity .45s ease}',
      /* ── THE BOX IS SQUARE AND THE SCREEN IS NOT ───────────────────────
         The region is 1.0002 as tall as it is wide, so the viewBox is 1000
         square. On a wide short window `meet` letterboxes it correctly and the
         ground image — which carries preserveAspectRatio="none" so it fills the
         viewBox exactly — was being stretched with it.
         The svg keeps its aspect and the wrap centres it, so the ground is
         never wider or taller than the ground. */
      '#amenti-attica .at-wrap{position:absolute;inset:0;display:flex;',
      '  flex-direction:column;padding:20px 244px 152px 26px;gap:0;',
      '  align-items:center}',
      /* `flex:1 1 auto` leaves the basis at auto, so the svg took its width
         from the row and aspect-ratio never got to decide anything — the
         region drew half as tall as it is. Basis zero, height from the row,
         WIDTH FROM THE ASPECT. A square region cannot then be drawn wide. */
      '#amenti-attica svg{flex:1 1 0;min-height:0;min-width:0;height:100%;',
      '  width:auto;max-width:100%;aspect-ratio:1/1;cursor:grab}',
      '#amenti-attica svg.at-drag{cursor:grabbing}',
      '#amenti-attica .at-ground{pointer-events:none}',
      /* A PIN. Small, hard, bright \u2014 the map's own value, so a reader crossing
         between the two surfaces reads the same mark. */
      '#amenti-attica .at-pin{fill:#5fd0e8;fill-opacity:.85;stroke:#081018;',
      '  stroke-width:.35;vector-effect:non-scaling-stroke;cursor:pointer}',
      '#amenti-attica .at-pin:hover{fill:#a9edff;fill-opacity:1}',
      /* AN OUTLINE IS NOT A FILL. A gable, a crenellation, a bay and a stele
         are strokes; only the settlement dot and the games oval carry a fill,
         and the oval is hollow so a track reads as a track. */
      '#amenti-attica .at-m-sacred,#amenti-attica .at-m-defence,',
      '#amenti-attica .at-m-harbour,#amenti-attica .at-m-worked,',
      '#amenti-attica .at-m-buried,#amenti-attica .at-m-built,',
      '#amenti-attica .at-m-ground,#amenti-attica .at-m-games{',
      '  fill:none;stroke:#5fd0e8;stroke-opacity:.8;stroke-width:.9;',
      '  vector-effect:non-scaling-stroke;stroke-linejoin:round;',
      '  stroke-linecap:round}',
      '#amenti-attica .at-m-ground{stroke:#8a9bb0;stroke-opacity:.6}',
      '#amenti-attica .at-m-harbour{stroke:#7fd8f0}',
      '#amenti-attica .at-pin:hover{stroke:#a9edff;stroke-opacity:1}',
      /* ── UNDATED IS NOT THE SAME CLAIM AS ATTESTED HERE ──────────────────
         705 of 1,746 places carry no span. They are drawn in every period,
         because Pleiades not knowing when is not the place not existing — but
         drawing them at full strength beside a place the register places IN
         this period would make the two look alike. Dimmer, and the count is
         stated. The same distinction as pin and wash, in a second dimension. */
      '#amenti-attica .at-undated .at-pin{fill:#7d8ea6;fill-opacity:.45}',
      '#amenti-attica .at-undated .at-name{opacity:.55}',
      /* named by more than one reading room: the mark holds, the name reads */
      '#amenti-attica .at-cited .at-pin{stroke-opacity:1;fill-opacity:1}',
      '#amenti-attica .at-cited .at-name{opacity:1;fill:#eaf6ff}',
      '#amenti-attica .at-mentioned .at-pin{stroke-opacity:.92}',
      /* A WASH. Soft, edgeless, never a point. Pleiades called it rough. */
      '#amenti-attica .at-wash{fill:#4a6c8f;fill-opacity:.14;stroke:none;',
      '  cursor:default}',
      '#amenti-attica .at-wash:hover{fill-opacity:.28}',
      /* brighter than the terrain at its palest, and the outline is a hint of
         separation rather than a box the letter sits inside */
      '#amenti-attica .at-name{fill:#eef4fb;text-anchor:middle;pointer-events:none;',
      '  opacity:0;paint-order:stroke;stroke:#05080e;stroke-opacity:.85;',
      '  stroke-linejoin:round;transition:opacity .3s ease}',
      '#amenti-attica .at-named .at-name{opacity:.95}',
      '#amenti-attica .at-head{display:flex;justify-content:space-between;',
      '  align-items:baseline;gap:20px;margin-bottom:10px;flex:0 0 auto}',
      '#amenti-attica .at-title{color:#8fa2ba;font-size:13px}',
      /* ── THE NOTE RAN UNDER THE BUTTONS ────────────────────────────────
         Five lines of prose in a flex column with no height budget, sitting
         behind the period row. It gets a bounded box that scrolls, and the
         controls get clear air beneath it. A caveat a reader cannot read is
         not a caveat. */
      /* ── THE NOTE WAS STILL UNDER THE BUTTONS ──────────────────────────
         Bounding it in the flex column was not enough: the column also holds
         the map, which takes what it can, so the note was pushed down onto the
         control row anyway. It comes OUT of the flow and gets its own strip
         above the buttons, and the wrap reserves the height for both. A caveat
         a reader cannot read is not a caveat, and this is the second attempt
         at the same sentence. */
      '#amenti-attica .at-note{position:absolute;left:26px;right:262px;',
      '  bottom:148px;color:#6f8098;font-size:11.5px;line-height:1.45;',
      '  max-height:52px;overflow-y:auto;z-index:5;',
      '  scrollbar-width:thin;scrollbar-color:#2b3a50 transparent}',
      '#amenti-attica .at-warn{color:#c99a4e}',
      /* THE SHORELINE IS THE MOST IMPORTANT SENTENCE ON THIS SURFACE and it
         was reading third. It goes first, and it is the only thing in amber. */
      '#amenti-attica .at-first{display:block;margin-bottom:3px}',
      '#amenti-attica .at-read{color:#f0f5fb;font-size:22px;letter-spacing:.01em;',
      '  font-variant-numeric:tabular-nums;white-space:nowrap}',
      '#amenti-attica .at-listhead{position:absolute;right:24px;top:56px;',
      '  z-index:7;font-size:10.5px;letter-spacing:.06em;color:#6f8098;',
      '  text-align:right;padding-bottom:6px;border-bottom:1px solid #1e2836;',
      '  width:220px}',
      '#amenti-attica .at-list{position:absolute;right:0;top:82px;bottom:156px;',
      '  width:232px;padding:8px 24px 12px 12px;overflow-y:auto;text-align:right;',
      '  background:linear-gradient(270deg,rgba(5,8,14,.94),rgba(5,8,14,0));',
      '  border-left:1px solid rgba(43,58,80,.5);scrollbar-width:thin}',
      '#amenti-attica .at-li{font-size:12px;line-height:1.5;color:#9fb1c7;',
      '  white-space:nowrap;overflow:hidden;text-overflow:ellipsis;cursor:default}',
      '#amenti-attica .at-li:hover,#amenti-attica .at-li.at-lit{color:#eaf6ff;',
      '  background:rgba(95,208,232,.08)}',
      /* ── THE LIST AND THE MAP POINT AT EACH OTHER ──────────────────────
         The names on the map are 5 px because a thousand of them must not
         collide; that is right for the map and wrong for READING. So the same
         places are listed at a legible size down the right, and hovering
         either end lights the other. The map answers WHERE, the list answers
         WHICH, and neither has to compromise.

         The lit mark GROWS — the one place on this surface where a mark
         changes size, and it is not a claim about the world, it is the
         reader's own pointer. */
      '#amenti-attica .at-seat.at-lit .at-pin{stroke:#a9edff;stroke-opacity:1;',
      '  fill-opacity:1;stroke-width:1.6}',
      '#amenti-attica .at-seat.at-lit{transform-box:fill-box;transform-origin:center}',
      '#amenti-attica .at-seat.at-lit .at-name{opacity:1;fill:#eaf6ff}',
      /* ── AN EVENT IS A MOMENT AND A PLACE IS NOT ────────────────────────
         Amber, and a burst rather than any of the nine place marks — the world
         map's own colour for something that HAPPENED, so a reader crossing
         between the two surfaces reads the same thing. Gold is not spent here;
         gold is a verified quote. */
      '#amenti-attica .at-ev{fill:none;stroke:#e0913f;stroke-width:1.3;',
      '  vector-effect:non-scaling-stroke;stroke-linecap:round;opacity:.9;',
      '  cursor:pointer}',
      '#amenti-attica .at-ev:hover{stroke:#ffc379;opacity:1}',
      '#amenti-attica .at-evname{fill:#e8bd83;text-anchor:middle;pointer-events:none;',
      '  paint-order:stroke;stroke:#05080e;stroke-opacity:.85;stroke-linejoin:round}',
      /* an authored coordinate is drawn dashed: this one stands on no place */
      '#amenti-attica .at-ev-loose{stroke-dasharray:2 2}',
      '#amenti-attica .at-halo{fill:none;stroke:#a9edff;stroke-width:1.2;',
      '  opacity:.65;vector-effect:non-scaling-stroke;pointer-events:none}',
      '#amenti-attica .at-li span{color:#5d6e84;font-size:10.5px}',
      '#amenti-attica .at-licited{color:#dbe8f5}',
      /* a small open rectangle after the name: this one is an area, not a
         point, and the wash on the map is the same claim */
      '#amenti-attica .at-liwash i{font-style:normal;color:#5b7794;',
      '  font-size:9px;padding-left:2px}',
      '#amenti-attica .at-licited span{color:#5fd0e8}',
      '#amenti-attica .at-ctl{position:absolute;left:26px;right:26px;bottom:16px;',
      '  z-index:6;display:flex;gap:8px;align-items:center;flex-wrap:wrap;',
      '  background:linear-gradient(0deg,rgba(5,8,14,.96) 60%,rgba(5,8,14,0));',
      '  padding-top:10px}',
      '#amenti-attica button{background:transparent;color:#8fa2ba;font:inherit;',
      '  font-size:11.5px;border:1px solid #23303f;border-radius:3px;',
      '  padding:5px 10px;cursor:pointer;letter-spacing:.05em}',
      '#amenti-attica button:hover{color:#c3d3e6;border-color:#33637a}',
      '#amenti-attica button[aria-pressed="true"]{color:#0a1018;background:#8fa8c4}',
      /* ── A KEY WITHOUT ITS TEXT IS WORSE THAN NO KEY ────────────────────
         Nine marks arrived and nothing said what they were. The world map met
         this on 4 September, when five legend entries overflowed the right
         edge and the amber diamond was left stranded with its words cut off —
         a reader sees a mark they cannot look up and assumes it means
         something. It wraps here, and it counts, so the key doubles as a
         census of what the period holds. */
      '#amenti-attica .at-key{position:absolute;left:26px;top:52px;z-index:6;',
      '  display:flex;flex-direction:column;gap:3px;font-size:10.5px;',
      '  color:#7d8ea6;background:rgba(5,8,14,.62);padding:9px 12px;',
      '  border:1px solid rgba(43,58,80,.5);border-radius:4px;letter-spacing:.03em}',
      '#amenti-attica .at-key div{display:flex;align-items:center;gap:7px;',
      '  cursor:pointer;white-space:nowrap}',
      '#amenti-attica .at-key div:hover{color:#dbe8f5}',
      '#amenti-attica .at-key div[aria-pressed="false"]{opacity:.34}',
      '#amenti-attica .at-key svg{width:13px;height:13px;overflow:visible;flex:0 0 13px}',
      '#amenti-attica .at-key b{color:#5d6e84;font-weight:400;margin-left:auto;',
      '  padding-left:8px;font-variant-numeric:tabular-nums}',
      /* ── THE SECOND CLOCK, KEPT VISIBLY APART FROM THE FIRST ────────────
         It sits above the period row and is labelled, because a reader who
         assumed one control moved everything would conclude the places were
         frozen or broken. Two controls, two registers, said out loud. */
      '#amenti-attica .at-clock{position:absolute;left:26px;right:262px;',
      '  bottom:118px;z-index:6;display:flex;gap:10px;align-items:center;',
      '  font-size:11px;color:#7d8ea6;letter-spacing:.04em}',
      '#amenti-attica .at-clocklab{flex:0 0 auto;color:#5d6e84}',
      '#amenti-attica .at-scrub{flex:1 1 auto;max-width:520px;accent-color:#e0913f;',
      '  height:3px;cursor:pointer}',
      '#amenti-attica .at-clockread{flex:0 0 auto;color:#e8bd83;min-width:9ch;',
      '  font-variant-numeric:tabular-nums}',
      '#amenti-attica .at-clockoff{flex:0 0 auto;font-size:10.5px;padding:3px 8px}',
      '#amenti-attica .at-hit{position:fixed;pointer-events:none;z-index:9;',
      '  background:rgba(8,12,20,.95);border:1px solid #2b3a50;border-radius:3px;',
      '  padding:7px 10px;font-size:11.5px;color:#dbe4f0;max-width:38ch;',
      '  opacity:0;transition:opacity .12s;white-space:pre-line}'
    ].join('\n');
    document.head.appendChild(s);
  }

  function mount() {
    if (el) { return el; }
    style();
    el = document.createElement('div');
    el.id = 'amenti-attica';
    el.innerHTML =
      '<div class="at-wrap">' +
        '<div class="at-head">' +
          '<div class="at-title">Attica \u00b7 a hundred miles from the Acropolis</div>' +
          '<div class="at-read"></div>' +
        '</div>' +
        '<svg viewBox="0 0 ' + VB + ' ' + VB + '" preserveAspectRatio="xMidYMid meet">' +
          '<g class="at-view">' +
            '<image class="at-ground" x="0" y="0" width="' + VB + '" height="' + VB + '" ' +
              'preserveAspectRatio="none"></image>' +
            '<g class="at-washes"></g><g class="at-pins"></g>' +
      '<g class="at-events"></g><g class="at-halo-g"></g>' +
          '</g>' +
        '</svg>' +
        '<div class="at-note"></div>' +
      '</div>' +
      '<div class="at-key"></div>' +
      '<div class="at-listhead"></div><div class="at-list"></div>' +
      '<div class="at-ctl">' +
        PERIODS.map(function (p) {
          return '<button type="button" data-p="' + p.k + '"' +
                 (p.k === 'all' ? ' aria-pressed="true"' : '') +
                 (p.when ? ' title="' + p.when + '"' : '') + '>' + p.label + '</button>';
        }).join('') +
        '<button type="button" data-z="out">\u2212</button>' +
        '<button type="button" data-z="in">+</button>' +
        '<button type="button" data-z="fit">fit</button>' +
      '</div>' +
      '<div class="at-clock">' +
        '<span class="at-clocklab">the year</span>' +
        '<input class="at-scrub" type="range" min="-520" max="320" step="1" value="-480">' +
        '<span class="at-clockread"></span>' +
        '<button type="button" class="at-clockoff" aria-pressed="true">off</button>' +
      '</div>' +
      '<div class="at-hit"></div>';
    document.body.appendChild(el);
    svg = el.querySelector('svg');
    view = el.querySelector('.at-view');
    wire();
    return el;
  }

  /* ── WHAT IS SHOWN AT A YEAR ────────────────────────────────────────────
     A place is drawn while the year sits inside its span. WITH `hi` NULL
     EVERYTHING IS DRAWN AND THE READOUT SAYS SO \u2014 1,746 at once is a smear,
     and a reader should be told that is what they are looking at rather than
     left to conclude the ground was that crowded.

     AND A PLACE WITH NO SPAN IS ALWAYS DRAWN. 705 of these carry no date,
     which is Pleiades not knowing rather than the place not existing. Hiding
     them at every year would be inventing an absence. */
  /* ── A PERIOD OVERLAPS A SPAN; A YEAR SAT INSIDE ONE ────────────────────
     The test is overlap, not containment. A place attested 550 BC to AD 300
     belongs to the Classical, Hellenistic AND Roman periods, and asking
     whether one year falls inside it would answer a question the register was
     never posed.

     AND A PLACE WITH NO SPAN IS ALWAYS DRAWN. 705 of 1,746 carry no date,
     which is Pleiades not knowing rather than the place not existing. Hiding
     them in every period would invent an absence. */
  function alive(r) {
    if (era.a === null) { return true; }
    if (r.from === null && r.until === null) { return true; }
    if (r.until !== null && r.until < era.a) { return false; }
    if (r.from !== null && r.from > era.b) { return false; }
    return true;
  }

  function draw() {
    if (!open || !rows) { return; }
    view.setAttribute('transform',
      'translate(' + TX.toFixed(2) + ' ' + TY.toFixed(2) + ') scale(' + K.toFixed(4) + ')');
    var iv = 1 / K;
    /* ── A LABEL IS NOT A MARK, AND MAY GROW ─────────────────────────────
       The rule that a mark does not get bigger is about CLAIMS: a pin means
       "here" at every scale, and swelling it would assert a size no register
       holds. A LABEL IS NOT A CLAIM ABOUT THE WORLD. It is text to read, and
       at ×1 it is 5 px because a thousand names are competing for the room.
       Zoom in and most of that competition leaves the screen, so the type can
       have the space it was denied.

       It grows on a LOGARITHM, not on K. Linear growth would put the marks
       back where the counter-scale took them from — 5 px at ×1 becoming 60 px
       at ×12 — and the surface would be a wall of type. This runs 5.0 px at ×1
       to about 8.6 px at ×12: legible, and still smaller than the list. */
    var TY = 5.0 * (1 + Math.log(Math.max(1, K)) * 0.22);
    var shown = rows.filter(alive);
    var pins = shown.filter(function (r) { return r.tier === 'pin'; });
    var wash = shown.filter(function (r) { return r.tier !== 'pin'; });

    /* washes first, and they are rectangles about their point because
       ATTICA.csv carries a representative coordinate rather than the bounding
       box. THAT IS A COMPROMISE AND IT IS STATED: the true extent is in
       Pleiades' bounding_box_wkt and is not harvested yet, so this draws a
       fixed soft area meaning "somewhere about here" rather than a false one
       meaning "exactly this rectangle". */
    var wh = '';
    wash.forEach(function (r) {
      var p = proj(r.lat, r.lon), a = 9 * iv;
      wh += '<rect class="at-wash" x="' + (p[0] - a).toFixed(2) + '" y="' + (p[1] - a).toFixed(2) +
            '" width="' + (a * 2).toFixed(2) + '" height="' + (a * 2).toFixed(2) +
            '" rx="' + (3 * iv).toFixed(2) + '" data-k="' + esc(r.key) + '"/>';
    });
    el.querySelector('.at-washes').innerHTML = wh;

    /* ── THE MARK HOLDS ITS SIZE AND SO DOES ITS OUTLINE ─────────────────
       Both divided by K, together. On 6 September the type was corrected and
       the outline was not, and at x14 a 0.23 px letter sat inside a 0.91 px
       stroke: every name on the world map drew as a black lozenge. The pair
       is one thing and moves as one. */
    var ph = '', placed = [], named = 0, dropped = 0, undated = 0;
    var tally = {};
    /* ── THE CULL RANKS BY CORROBORATION, THEN BY NEARNESS ────────────────
       Sorting by distance alone put the Acropolis' own gates first and Delphi
       nowhere, because the cull lays out greedily and the near ones take the
       room. THE CORPUS KNOWS WHICH PLACES CARRY THE STORY — Athens in 61
       reading rooms, Corinth in 27, Delphi in 24 — so a place named by many
       sources gets its label before a farmstead two hundred metres from the
       centre. Without the mentions file this falls back to distance, which is
       what it did before. */
    pins.sort(function (a, b) {
      var ma = mentions && mentions[a.key], mb = mentions && mentions[b.key];
      var sa = ma ? ma.src : 0, sb = mb ? mb.src : 0;
      if (sa !== sb) { return sb - sa; }
      return (+a.km) - (+b.km);
    });
    pins.forEach(function (r) {
      var p = proj(r.lat, r.lon);
      var fit = true, w = (r.name || '').length * (TY * 0.32) * iv;
      for (var i = 0; i < placed.length; i++) {
        if (Math.abs(p[0] - placed[i][0]) < (w + placed[i][2]) &&
            Math.abs(p[1] - placed[i][1]) < TY * 1.4 * iv) { fit = false; break; }
      }
      if (fit && K >= 1.8) { placed.push([p[0], p[1], w]); named++; } else { fit = false; dropped++; }
      var und = (r.from === null && r.until === null);
      if (und) { undated++; }
      var m = markOf(r.kind);
      tally[m] = (tally[m] || 0) + 1;
      if (offMarks[m]) { return; }
      var a = 1.9 * iv, d = shape(m, a);
      var body;
      if (d) {
        body = '<path class="at-pin at-m-' + m + '" d="' + d + '" transform="translate(' +
               p[0].toFixed(2) + ' ' + p[1].toFixed(2) + ')" data-k="' + esc(r.key) + '"/>';
      } else if (m === 'games') {
        body = '<ellipse class="at-pin at-m-games" cx="' + p[0].toFixed(2) + '" cy="' +
               p[1].toFixed(2) + '" rx="' + (a * 1.15).toFixed(2) + '" ry="' +
               (a * .68).toFixed(2) + '" data-k="' + esc(r.key) + '"/>';
      } else {
        body = '<circle class="at-pin at-m-' + m + '" cx="' + p[0].toFixed(2) + '" cy="' +
               p[1].toFixed(2) + '" r="' + (1.5 * iv).toFixed(2) + '" data-k="' + esc(r.key) + '"/>';
      }
      /* ── CORROBORATED IS BRIGHTER, AND IT IS NOT A SECOND KIND OF PLACE ──
         A place the corpus names is the same place; what changes is how much
         stands behind it. So the MARK does not change — a harbour is a
         crescent whether Thucydides mentions it or not — only its weight. Two
         sources or more and it holds full strength; the rest sit back. */
      var mn = mentions && mentions[r.key];
      ph += '<g class="at-seat at-' + m + (fit ? ' at-named' : '') +
            (und ? ' at-undated' : '') +
            (mn ? (mn.src > 1 ? ' at-cited' : ' at-mentioned') : '') +
            '" data-k="' + esc(r.key) + '">' + body +
            /* THE OUTLINE MOVES WITH THE TYPE. Sized from TY, not from a
               constant — the world map corrected its font on 6 September and
               left the stroke behind, and every name drew as a black lozenge
               at ×14. One pair, one number. */
            /* ── THE HALO ATE THE LETTER · found 7 Sep ────────────────────
               At 0.30 of the font the stroke is 2.3 px on a 7.7 px face, which
               is 1.15 px EACH SIDE of the glyph outline — and a monospace stem
               at that size is about 1 px wide. The outline met itself in the
               middle and every name drew solid dark: invisible on pale
               terrain, fine on the sea, which is why it looked like the labels
               were flipping colour as the map moved.

               THE WORLD MAP'S LOZENGE WAS THE SAME FAULT AT FOUR TIMES THE
               SCALE. Its ratio of 0.29 survived only because 5.6 px type has
               slightly fatter stems than 7.7 px type has room for. 0.17 leaves
               the stem clear at every size this surface draws. */
            (fit ? '<text class="at-name" x="' + p[0].toFixed(2) + '" y="' +
                   (p[1] - TY * 0.68 * iv).toFixed(2) + '" style="font-size:' +
                   (TY * iv).toFixed(3) + 'px;stroke-width:' +
                   (TY * 0.17 * iv).toFixed(3) + 'px">' +
                   esc(r.name) + '</text>' : '') +
            '</g>';
    });
    el.querySelector('.at-pins').innerHTML = ph;

    var cr = el.querySelector('.at-clockread');
    if (cr) {
      cr.textContent = scrub === null ? 'the whole period' : yr(scrub);
    }
    el.querySelector('.at-read').textContent =
      era.a === null ? 'the whole register' : era.label + '  \u00b7  ' + era.when;
    el.querySelector('.at-note').innerHTML =
      '<span class="at-warn at-first">Every shoreline here is TODAY\u2019S. ' +
      'Thermopylae\u2019s has moved six kilometres since 480 BC; Piraeus, Eleusis and ' +
      'Marathon are silted harbours.</span>' +
      shown.length + ' of ' + rows.length + ' places \u00b7 ' + pins.length + ' pinned \u00b7 ' +
      wash.length + ' somewhere in an area \u00b7 ' +
      /* NOTHING NAMED IS CORRECT AND LOOKS BROKEN. At x1 with the whole
         register on, every one of 1,567 labels collides and the cull drops
         them all \u2014 which is the right answer and reads as a fault. It says so. */
      (named ? named + ' named' : '<b>nothing named at this zoom</b> \u2014 every ' +
               'label collides; zoom past \u00d71.8') +
      (named && dropped ? ', ' + dropped + ' with no room' : '') +
      (undated ? ' \u00b7 <b>' + undated + ' undated</b>, drawn dim in every period: ' +
                 'Pleiades not knowing WHEN is not the place not existing' : '') +
      (era.a === null
        ? ' \u00b7 <b>all of it at once, which is a smear</b> \u2014 pick a period'
        : ' \u00b7 <b>five periods, not years</b> \u2014 \u201cClassical\u201d is dated ' +
          '550\u2013330 BC because a range needs a number, and most spans cross every ' +
          'period, so this filters less than it looks like it should') +
      (mentions
        ? ' \u00b7 <b>' + shown.filter(function (x) { return mentions[x.key]; }).length +
          ' named in the library</b>, of 603 texts and 35.9 M characters \u2014 ' +
          'labels go to the corroborated first'
        : (mentionsErr
            ? ' \u00b7 ATTICA-MENTIONS.csv not read (' + esc(mentionsErr) + '), so nothing ' +
              'here knows which places the corpus names'
            : '')) +
      (events ? ' \u00b7 <b>' + evn + ' event' + (evn === 1 ? '' : 's') +
                '</b> on the ground they happened on, authored' +
                (scrub !== null
                  ? ' \u00b7 <b>the year moves the events only</b> \u2014 a place here is ' +
                    'dated to a PERIOD, so scrubbing cannot move it and pretending ' +
                    'otherwise would animate a register that is standing still'
                  : '') : '') +
      ' \u00b7 Pleiades CC BY 3.0 \u00b7 land 30 m Copernicus, sea 462 m ETOPO.';

    /* ── THE EVENTS, ON THE GROUND THEY HAPPENED ON ──────────────────────
       An event belongs to a period if its year sits INSIDE it — a containment
       test, and correct here unlike the places, whose spans are period bands
       and are tested by overlap. A moment has a year; a place has a stretch of
       centuries, and asking the same question of both would be wrong twice. */
    var eg = el.querySelector('.at-events'), eh = '', evn = 0;
    if (eg) {
      if (events) {
        events.forEach(function (v) {
          if (era.a !== null && (v.year < era.a || v.year > era.b)) { return; }
          /* ── IT FADES WITH DISTANCE IN YEARS, IT DOES NOT VANISH ─────────
             At the scrubbed year an event is at full strength; forty years
             either side it is a trace. It is never hidden, because a reader
             moving through time should see what is coming and what has just
             passed — and because a mark that blinks out asserts that nothing
             happened, which is a claim about silence the register cannot
             make. */
          var d = scrub === null ? 0 : Math.abs(v.year - scrub);
          var glow = scrub === null ? 1 : Math.max(0.1, 1 - d / FADE);
          evn++;
          var p = proj(v.lat, v.lon), a = 3.4 * iv * (0.75 + 0.45 * glow);
          var d = 'M0 ' + (-a).toFixed(2) + 'v' + (a * 0.55).toFixed(2) +
                  'M0 ' + a.toFixed(2) + 'v' + (-a * 0.55).toFixed(2) +
                  'M' + (-a).toFixed(2) + ' 0h' + (a * 0.55).toFixed(2) +
                  'M' + a.toFixed(2) + ' 0h' + (-a * 0.55).toFixed(2);
          eh += '<g class="at-evg" data-e="' + esc(v.name) + '" style="opacity:' +
                (0.22 + 0.78 * glow).toFixed(3) + '">' +
                '<circle class="at-ev' + (v.at ? '' : ' at-ev-loose') + '" cx="' +
                p[0].toFixed(2) + '" cy="' + p[1].toFixed(2) + '" r="' +
                (a * 0.62).toFixed(2) + '"/>' +
                '<path class="at-ev" transform="translate(' + p[0].toFixed(2) + ' ' +
                p[1].toFixed(2) + ')" d="' + d + '"/>' +
                (K >= 2.2 || glow > 0.75
                  ? '<text class="at-evname" x="' + p[0].toFixed(2) + '" y="' +
                    (p[1] + TY * 1.6 * iv).toFixed(2) + '" style="font-size:' +
                    (TY * 0.92 * iv).toFixed(3) + 'px;stroke-width:' +
                    (TY * 0.17 * iv).toFixed(3) + 'px">' + esc(v.name) + '</text>'
                  : '') +
                '</g>';
        });
      }
      eg.innerHTML = eh;
    }

    /* the ring is redrawn with the frame so it stays on its place through a
       pan or a zoom — it is a pointer, and a pointer that lags is worse than
       none */
    haloAt(litKey);

    /* THE KEY DRAWS ITS SWATCHES WITH THE SAME shape() THE MAP USES. Two
       drawings of one mark would drift the first time either changed, and a
       legend that disagrees with the surface is worse than none. */
    var key = el.querySelector('.at-key');
    if (key && !key._built) {
      key._built = true;
      key.innerHTML = KEY.map(function (o) {
        var d = shape(o.k, 5);
        var body = d
          ? '<path d="' + d + '" fill="none" stroke="currentColor" stroke-width="1.2" ' +
            'stroke-linejoin="round" stroke-linecap="round" transform="translate(6.5 6.5)"/>'
          : (o.k === 'games'
              ? '<ellipse cx="6.5" cy="6.5" rx="5.8" ry="3.4" fill="none" ' +
                'stroke="currentColor" stroke-width="1.2"/>'
              : '<circle cx="6.5" cy="6.5" r="3" fill="currentColor"/>');
        return '<div data-m="' + o.k + '" aria-pressed="true" title="' + esc(o.eg) + '">' +
               '<svg viewBox="0 0 13 13">' + body + '</svg>' + o.label +
               '<b data-n="' + o.k + '"></b></div>';
      }).join('');
      key.addEventListener('click', function (e) {
        var d = e.target.closest ? e.target.closest('[data-m]') : null;
        if (!d) { return; }
        var m = d.getAttribute('data-m');
        if (offMarks[m]) { delete offMarks[m]; } else { offMarks[m] = 1; }
        d.setAttribute('aria-pressed', offMarks[m] ? 'false' : 'true');
        draw();
      });
    }
    if (key) {
      KEY.forEach(function (o) {
        var b = key.querySelector('b[data-n="' + o.k + '"]');
        if (b) { b.textContent = tally[o.k] || 0; }
      });
    }

    var lh = el.querySelector('.at-listhead');
    if (lh) {
      lh.textContent = (mentions ? 'most named first' : 'nearest first') +
        ' \u00b7 ' + pins.length + ' pinned, ' + wash.length + ' area' +
        (wash.length === 1 ? '' : 's');
    }
    /* ── THE MOST-NAMED PLACE WAS MISSING FROM THE LIST OF MOST-NAMED ─────
       The column showed pins only, and `Athenae` is a WASH — Pleiades records
       the city as an area rather than a point, which is correct and is why it
       has no dot. So Athens, named in 61 reading rooms against Corinth's 27,
       did not appear at all, and a reader scanning for it would conclude the
       corpus is silent on Athens.

       An area is not a lesser place. It is listed with everything else and
       says what it is, because THAT IT IS AN AREA IS INFORMATION AND NOT A
       REASON TO HIDE IT. The mark still differs on the map; only the ranking
       stops caring. */
    var listed = shown.slice().sort(function (a, b) {
      var ma = mentions && mentions[a.key], mb = mentions && mentions[b.key];
      var sa = ma ? ma.src : 0, sb = mb ? mb.src : 0;
      if (sa !== sb) { return sb - sa; }
      return (+a.km) - (+b.km);
    });

    var lb = el.querySelector('.at-list');
    lb.innerHTML = listed.slice(0, 90).map(function (r) {
      var mn = mentions && mentions[r.key];
      var isWash = r.tier !== 'pin';
      return '<div class="at-li' + (mn && mn.src > 1 ? ' at-licited' : '') +
             (isWash ? ' at-liwash' : '') +
             '" data-k="' + esc(r.key) + '" title="' +
             (isWash ? 'somewhere in this area \u2014 no single position' : '') + '">' +
             esc(r.name) + (isWash ? ' <i>\u25ad</i>' : '') +
             ' <span>' + (mn ? mn.src + ' room' + (mn.src === 1 ? '' : 's')
                             : r.km + ' km') + '</span></div>';
    }).join('') || '<div class="at-li">nothing in this year</div>';
  }

  var litKey = null;
  /* pressing a key entry hides that kind. A reader looking for harbours should
     be able to see only harbours, and the count stays visible either way so
     nothing is hidden without saying how much. */
  var offMarks = {};
  var KEY = [
    { k: 'settled', label: 'settled',  eg: 'settlement, deme, village' },
    { k: 'sacred',  label: 'sacred',   eg: 'temple, sanctuary, shrine, acropolis' },
    { k: 'built',   label: 'built',    eg: 'stoa, basilica, library, bath' },
    { k: 'defence', label: 'defence',  eg: 'fort, tower, wall, gate' },
    { k: 'harbour', label: 'harbour',  eg: 'port, limen, mole' },
    { k: 'games',   label: 'games',    eg: 'theatre, stadium, gymnasion, odeon' },
    { k: 'worked',  label: 'worked',   eg: 'mine, quarry, kiln' },
    { k: 'buried',  label: 'buried',   eg: 'tomb, necropolis, tumulus' },
    { k: 'ground',  label: 'ground',   eg: 'mountain, cape, river, island' },
    { k: 'other',   label: 'other',    eg: 'region, province, map label' }
  ];

  /* ── LIGHTING BOTH ENDS ─────────────────────────────────────────────────
     Delegated rather than bound, because both the list and the marks are
     rebuilt on every draw and a listener attached to a node would die with it.
     That is the world map's own lesson, kept. */
  function light(key) {
    if (key === litKey) { return; }
    litKey = key;
    el.querySelectorAll('.at-lit').forEach(function (n) { n.classList.remove('at-lit'); });
    if (key) {
      el.querySelectorAll('[data-k="' + String(key).replace(/"/g, '') + '"]')
        .forEach(function (n) {
          n.classList.add('at-lit');
          if (n.classList.contains('at-li') && n.scrollIntoView) {
            var box = n.getBoundingClientRect(), par = n.parentNode.getBoundingClientRect();
            if (box.top < par.top || box.bottom > par.bottom) {
              n.scrollIntoView({ block: 'nearest' });
            }
          }
        });
    }
    haloAt(key);
  }

  /* A RING ROUND THE LIT PLACE. The marks themselves never grow — a mark
     stands for a claim and a claim does not get bigger — so the ring carries
     the pointing instead, and it is plainly not one of the map's own marks. */
  function haloAt(key) {
    var g = el.querySelector('.at-halo-g');
    if (!g) { return; }
    if (!key || !rows) { g.innerHTML = ''; return; }
    var r = rows.filter(function (x) { return x.key === key; })[0];
    if (!r || !alive(r)) { g.innerHTML = ''; return; }
    var p = proj(r.lat, r.lon), a = 6 / K;
    g.innerHTML = '<circle class="at-halo" cx="' + p[0].toFixed(2) + '" cy="' +
                  p[1].toFixed(2) + '" r="' + a.toFixed(2) + '"/>';
  }

  function wire() {
    var hit = el.querySelector('.at-hit');
    el.addEventListener('pointerover', function (e) {
      var n = e.target.closest ? e.target.closest('[data-k]') : null;
      light(n ? n.getAttribute('data-k') : null);
      var ev = e.target.closest ? e.target.closest('[data-e]') : null;
      if (ev && events) {
        var nm = ev.getAttribute('data-e');
        var v = events.filter(function (x) { return x.name === nm; })[0];
        if (v) {
          hit.textContent = v.name + '\n' + yr(v.year) + '  ·  ' + (v.category || '') +
            (v.where ? '\n' + v.where : '') +
            (v.note ? '\n\n' + v.note : '') +
            (v.at ? '' : '\n\n— authored coordinate: this stands on no place in the ' +
                         'register, and a sea-fight has no single position');
          hit.style.opacity = 1;
        }
      }
    });
    el.addEventListener('pointerleave', function () { light(null); });
    el.addEventListener('pointerover', function (e) {
      var n = e.target.closest ? e.target.closest('[data-k]') : null;
      if (!n) { hit.style.opacity = 0; return; }
      var r = rows && rows.filter(function (x) { return x.key === n.getAttribute('data-k'); })[0];
      if (!r) { return; }
      hit.textContent = r.name + '\n' + (r.kind || '') +
        '\n' + (r.tier === 'pin' ? 'a position' : 'somewhere in this area') +
        (r.from !== null || r.until !== null
          ? '\nattested ' + (r.from !== null ? yr(r.from) : '?') + ' to ' +
            (r.until !== null ? yr(r.until) : '?')
          : '\nno date in the register') +
        '\n' + r.km + ' km from the Acropolis' +
        (function () {
          var mn = mentions && mentions[r.key];
          if (!mn) {
            return mentions ? '\n\nnamed by nothing in the library' : '';
          }
          return '\n\nnamed ' + mn.n + ' time' + (mn.n === 1 ? '' : 's') +
                 ' in ' + mn.src + ' reading room' + (mn.src === 1 ? '' : 's') +
                 (mn.where ? '\n' + mn.where.replace(/;/g, '\n') : '');
        })();
      hit.style.opacity = 1;
    });
    el.addEventListener('pointermove', function (e) {
      hit.style.left = (e.clientX + 14) + 'px';
      hit.style.top = (e.clientY + 14) + 'px';
    });

    var sc = el.querySelector('.at-scrub'), so = el.querySelector('.at-clockoff');
    if (sc) {
      sc.addEventListener('input', function () {
        scrub = +sc.value;
        so.setAttribute('aria-pressed', 'false');
        so.textContent = 'off';
        draw();
      });
    }
    if (so) {
      so.addEventListener('click', function () {
        scrub = (scrub === null) ? +sc.value : null;
        so.setAttribute('aria-pressed', scrub === null ? 'true' : 'false');
        draw();
      });
    }

    el.querySelectorAll('.at-ctl button').forEach(function (b) {
      b.addEventListener('click', function (ev) {
        ev.stopPropagation();
        var pk = b.getAttribute('data-p'), z = b.getAttribute('data-z');
        if (pk !== null) {
          era = PERIODS.filter(function (p) { return p.k === pk; })[0] || PERIODS[0];
          el.querySelectorAll('.at-ctl button[data-p]').forEach(function (o) {
            o.setAttribute('aria-pressed', o === b ? 'true' : 'false');
          });
        } else if (z === 'fit') {
          K = 1; TX = 0; TY = 0;
        } else {
          zoom(z === 'in' ? 1.5 : 1 / 1.5);
        }
        draw();
      });
    });

    function zoom(f, cx, cy) {
      var r = svg.getBoundingClientRect();
      if (!r.width) { return; }
      var mx = cx == null ? VB / 2 : (cx - r.left) / r.width * VB;
      var my = cy == null ? VB / 2 : (cy - r.top) / r.height * VB;
      var wx = (mx - TX) / K, wy = (my - TY) / K;
      var k = Math.max(K_MIN, Math.min(K_MAX, K * f));
      if (k === K) { return; }
      K = k; TX = mx - wx * K; TY = my - wy * K;
      clamp();
    }
    function clamp() {
      var m = VB - VB * K;
      TX = Math.min(0, Math.max(m, TX));
      TY = Math.min(0, Math.max(m, TY));
    }
    el.addEventListener('wheel', function (e) {
      e.preventDefault();
      zoom(e.deltaY > 0 ? 0.88 : 1.14, e.clientX, e.clientY);
      draw();
    }, { passive: false });

    var pan = false, px = 0, py = 0;
    el.addEventListener('pointerdown', function (e) {
      if (e.target.closest && e.target.closest('.at-ctl,.at-list')) { return; }
      pan = true; px = e.clientX; py = e.clientY;
      svg.classList.add('at-drag');
    });
    el.addEventListener('pointermove', function (e) {
      if (!pan) { return; }
      var r = svg.getBoundingClientRect();
      TX += (e.clientX - px) / r.width * VB;
      TY += (e.clientY - py) / r.height * VB;
      px = e.clientX; py = e.clientY;
      clamp(); draw();
    });
    ['pointerup', 'pointercancel'].forEach(function (t) {
      el.addEventListener(t, function () { pan = false; svg.classList.remove('at-drag'); });
    });
    el.addEventListener('dblclick', function () { K = 1; TX = 0; TY = 0; draw(); });
    ['click', 'pointerdown'].forEach(function (t) {
      el.addEventListener(t, function (e) { e.stopPropagation(); });
    });
    document.addEventListener('keydown', function (e) {
      if (e.key === 'Escape' && document.body.classList.contains('scene-attica')) {
        e.stopPropagation();
        hide();
        if (window.AmentiMap && window.AmentiMap.syncRail) { window.AmentiMap.syncRail(); }
      }
    }, true);
  }

  function show() {
    mount();
    /* the two instruments never share the screen \u2014 the map's own rule, kept */
    document.body.classList.remove('scene-bare', 'scene-map');
    document.body.classList.add('scene-attica');
    open = true;

    var img = el.querySelector('.at-ground');
    if (!img.getAttribute('href')) {
      img.addEventListener('error', function () {
        el.querySelector('.at-note').innerHTML =
          '<span class="at-warn">ATTICA.jpg did not load \u2014 the places are drawn on ' +
          'nothing. That is a chart without ground, which is what this was before ' +
          'the ground existed. Nothing is drawn in its place.</span>';
      });
      img.setAttribute('href', RAW + 'ATTICA.jpg');
    }
    if (events === null && eventsErr === null) {
      fetch(RAW + 'ATTICA-EVENTS.csv?_=' + Date.now())
        .then(function (r) { return r.ok ? r.text() : null; })
        .then(function (t) {
          if (!t) { eventsErr = 'not in the repo yet'; return; }
          var lines = t.replace(/\r\n/g, '\n').split('\n');
          var cols = split(lines[0]), out = [];
          for (var i = 1; i < lines.length; i++) {
            var l = lines[i];
            if (!l.trim() || l.replace(/^\s+/, '').charAt(0) === '#') { continue; }
            var c = split(l), o = {};
            for (var j = 0; j < cols.length; j++) { o[cols[j]] = c[j] == null ? '' : c[j]; }
            o.year = +o.year; o.lat = +o.lat; o.lon = +o.lon;
            if (!isNaN(o.year) && !isNaN(o.lat) && !isNaN(o.lon)) { out.push(o); }
          }
          events = out;
          draw();
        })
        .catch(function (e) { eventsErr = e.message; });
    }
    if (mentions === null && mentionsErr === null) {
      fetch(RAW + 'ATTICA-MENTIONS.csv?_=' + Date.now())
        .then(function (r) { return r.ok ? r.text() : null; })
        .then(function (t) {
          if (!t) { mentionsErr = 'not in the repo yet'; return; }
          mentions = {};
          var lines = t.replace(/\r\n/g, '\n').split('\n');
          var cols = split(lines[0]);
          for (var i = 1; i < lines.length; i++) {
            if (!lines[i].trim()) { continue; }
            var c = split(lines[i]), o = {};
            for (var j = 0; j < cols.length; j++) { o[cols[j]] = c[j] == null ? '' : c[j]; }
            if (o.key && +o.mentions > 0) {
              mentions[o.key] = { n: +o.mentions, src: +o.sources,
                                  where: o['in'] || '', snip: o.first_seen || '' };
            }
          }
          draw();
        })
        .catch(function (e) { mentionsErr = e.message; });
    }
    if (rows === null && loadErr === null) {
      fetch(RAW + 'ATTICA.csv?_=' + Date.now())
        .then(function (r) { if (!r.ok) { throw new Error('HTTP ' + r.status); } return r.text(); })
        .then(function (t) { rows = parse(t); draw(); })
        .catch(function (e) {
          loadErr = e.message;
          el.querySelector('.at-note').innerHTML =
            '<span class="at-warn">ATTICA.csv did not load (' + esc(e.message) +
            '). The ground is drawn and nothing is on it \u2014 which is the register ' +
            'missing, not the places being absent.</span>';
        });
    }
    draw();
    return true;
  }

  function hide() {
    open = false;
    document.body.classList.remove('scene-attica');
  }
  function toggle() { return open ? (hide(), false) : show(); }

  /* an olive leaf and a coast \u2014 a place, not a world */
  var ICON =
    '<svg viewBox="0 0 24 24" aria-hidden="true">' +
    '<path d="M4 17c4-1 7-4 9-8"/><path d="M13 9c2 0 4 1 5 3"/>' +
    '<path d="M3 21h18"/></svg>';

  function join() {
    if (!window.AmentiMap || !window.AmentiMap.addFaculty) { return false; }
    window.AmentiMap.addFaculty('fac-attica', 'attica', ICON, toggle,
                                function () { return open; });
    return true;
  }
  function arrive(n) {
    if (join()) { return; }
    if ((n || 0) > 40) {
      console.log('ATTICA did not join the rail \u2014 AmentiMap.addFaculty was never ' +
                  'exported. amenti-attica.js needs amenti-map.js loaded first.');
      return;
    }
    setTimeout(function () { arrive((n || 0) + 1); }, 250);
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', function () { arrive(0); });
  } else {
    arrive(0);
  }

  window.AmentiAttica = {
    show: show, hide: hide, toggle: toggle,
    isOpen: function () { return open; },
    /* the periods by key: all arch clas hell rome late */
    period: function (k) {
      era = PERIODS.filter(function (p) { return p.k === k; })[0] || PERIODS[0];
      draw();
      return { key: era.k, from: era.a, until: era.b };
    },
    periods: function () { return PERIODS.map(function (p) { return p.k; }); },
    count: function () {
      return rows ? { places: rows.length, shown: rows.filter(alive).length,
                      pin: rows.filter(function (r) { return r.tier === 'pin'; }).length }
                  : (loadErr ? { error: loadErr } : null);
    }
  };
})();
