/* ============================================================================
   amenti-ground.js  ·  THE FLOOR
   ----------------------------------------------------------------------------
   Puts GROUND.jpg under the map: computed relief AND bathymetry, in the map's
   own equirectangular projection, generated by tools/render-ground.py from
   ETOPO 2022.

   ── WHY IT IS NOT THE ATLAS ───────────────────────────────────────────────
   The first attempt pointed `.mp-relief` at this image, because an <image>
   element was already sitting there. It came out wrong, and the reason was
   not the picture:

       .mp-relief is CLIPPED TO url(#mp-landclip) — WORLD.json's baked land
       path — because Natural Earth's shaded relief stops at the coastline and
       an unclipped one would put modelling on an ocean floor it does not have.

   That clip is correct for the atlas and it THROWS AWAY THE ENTIRE REASON THIS
   IMAGE EXISTS. GROUND.jpg has a sea floor: the shelf around the Aegean
   islands, the deep Ionian basin, the Hellenic Trench south of Crete. Clipped
   to land, none of it can be seen, and in any Mediterranean view that is most
   of the screen.

   Borrowing a slot because an element was already there is the same mistake as
   writing a seat's name into the glyph because it was the first <text> in the
   group. THE ATLAS IS A PICTURE YOU SWITCH ON TO SEE TERRAIN BEHIND THE CHART.
   THIS IS THE CHART'S FLOOR. Two things, two layers, two buttons.

   ── AND IT IS A MODULE ────────────────────────────────────────────────────
   One script tag in hall.html and NO EDIT TO amenti-map.js. It joins the rail
   through AmentiMap.addFaculty, beside the globe and the glass, and it inserts
   its own <image> INSIDE .mp-view so it rides the camera — appended before the
   first mark layer so everything the map draws stays on top of it.

   The atlas is untouched. Both can be on; the ground sits beneath.
   ========================================================================== */
(function () {
  'use strict';

  var SVGNS = 'http://www.w3.org/2000/svg';
  var RAW = 'https://raw.githubusercontent.com/ianingram/Amenti.live/main/';
  var img = null, open = false, loaded = false, failed = null;

  function style() {
    if (document.getElementById('mp-ground-css')) return;
    var s = document.createElement('style');
    s.id = 'mp-ground-css';
    s.textContent = [
      /* NOT CLIPPED. That is the whole difference from the atlas. */
      '#amenti-map .mp-ground{pointer-events:none;opacity:0;',
      '  transition:opacity .5s ease}',
      '#amenti-map.mp-hasground .mp-ground{opacity:.9}',
      /* THE DRAWN SEA STANDS DOWN WHEN THE REAL ONE ARRIVES. .mp-sea is a flat
         rect the colour of deep water, and it exists because there was nothing
         better. With a floor underneath it would be a lid over the thing it
         was standing in for. */
      '#amenti-map.mp-hasground .mp-sea{opacity:0}',
      /* the coastline stays, and matters more rather than less: the shore is
         a claim about where land ends, and a raster edge is not that claim */
      '#amenti-map.mp-hasground .mp-land{fill:none}'
    ].join('\n');
    document.head.appendChild(s);
  }

  /* ── WHERE IT GOES IN THE STACK ─────────────────────────────────────────
     Inside .mp-view so it pans and zooms with the world, and BEFORE the first
     drawing layer so every mark stays above it. It is inserted after the
     graticule if there is one, so the grid reads over the ground rather than
     under it \u2014 a graticule is a reading aid and belongs with the marks. */
  function mount() {
    var view = document.querySelector('#amenti-map .mp-view');
    if (!view) return false;
    if (img && view.contains(img)) return true;
    style();
    img = document.createElementNS(SVGNS, 'image');
    img.setAttribute('class', 'mp-ground');
    img.setAttribute('x', '0'); img.setAttribute('y', '0');
    img.setAttribute('width', '1000'); img.setAttribute('height', '500');
    img.setAttribute('preserveAspectRatio', 'none');
    /* ── BRACES, AND A REFERENCE THAT CANNOT BE NULL ─────────────────────
       This was a braceless if/else and Safari reported a syntax error on the
       `else`. The file parsed in every other reader, so the diagnosis is
       uncertain — but an unbraced pair saves nothing and an insertion point
       computed from `view.firstChild.nextSibling` can be null on a subtree
       this file does not own. Both are removed rather than argued with. */
    var grat = view.querySelector('.mp-graticule');
    var before = null;
    if (grat) {
      before = grat.nextSibling;
    }
    if (!before) {
      before = view.querySelector('.mp-land') || view.querySelector('.mp-coast');
    }
    if (before) {
      view.insertBefore(img, before);
    } else {
      view.appendChild(img);
    }
    return true;
  }

  function show() {
    if (!document.body.classList.contains('scene-map')) {
      console.log('THE GROUND cannot open \u2014 the map is closed.');
      return false;
    }
    if (!mount()) {
      console.log('THE GROUND cannot open \u2014 no .mp-view. The map has not drawn yet.');
      return false;
    }
    var el = document.querySelector('#amenti-map');
    if (!loaded) {
      /* ── IT IS 5.7 MB AND THE FETCH IS THE FIRST PRESS, NOT THE LOAD ─────
         The blueprint pays nothing for a floor nobody asked for, exactly as
         the atlas pays nothing for its relief until pressed. And if it will
         not load, the map is a chart without a floor \u2014 which is what it was
         an hour ago and still true. No fallback, no apology, nothing drawn in
         its place, and the reason stated once. */
      img.addEventListener('error', function () {
        failed = 'the image did not load';
        el.classList.remove('mp-hasground');
        console.log('THE GROUND: GROUND.jpg did not load. The map is a chart ' +
                    'without a floor, which is what it was before. Nothing is drawn ' +
                    'in its place.');
      });
      img.addEventListener('load', function () { loaded = true; });
      img.setAttribute('href', RAW + 'GROUND.jpg');
    }
    el.classList.add('mp-hasground');
    open = true;
    return true;
  }

  function hide() {
    open = false;
    var el = document.querySelector('#amenti-map');
    if (el) el.classList.remove('mp-hasground');
  }
  function toggle() { return open ? (hide(), false) : show(); }

  /* a contour and a waterline — ground and the sea over it. Not a globe, which
     is the map itself, and not a lens, which is the glass. */
  var ICON =
    '<svg viewBox="0 0 24 24" aria-hidden="true">' +
    '<path d="M3 16.5c3-4 5-1 8-5s6-2 10-5"/>' +
    '<path d="M3 20.5h18"/></svg>';

  function join() {
    if (!window.AmentiMap || !window.AmentiMap.addFaculty) return false;
    window.AmentiMap.addFaculty('fac-ground', 'ground', ICON, toggle,
                                function () { return open; });
    return true;
  }
  function arrive(n) {
    if (join()) return;
    if ((n || 0) > 40) {
      console.log('THE GROUND did not join the rail \u2014 AmentiMap.addFaculty was never ' +
                  'exported. amenti-ground.js needs amenti-map.js loaded first.');
      return;
    }
    setTimeout(function () { arrive((n || 0) + 1); }, 250);
  }
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', function () { arrive(0); });
  } else {
    arrive(0);
  }

  /* the map rebuilds nothing this file owns, but it does redraw \u2014 and a
     redraw must not lose the floor */
  var mo = new MutationObserver(function () {
    if (open) mount();
    if (open && !document.body.classList.contains('scene-map')) {
      hide();
      if (window.AmentiMap && window.AmentiMap.syncRail) window.AmentiMap.syncRail();
    }
  });
  mo.observe(document.body, { attributes: true, attributeFilter: ['class'] });

  window.AmentiGround = {
    show: show, hide: hide, toggle: toggle,
    isOpen: function () { return open; },
    state: function () {
      return { open: open, loaded: loaded, failed: failed,
               mounted: !!(img && img.parentNode) };
    }
  };
})();
