#!/usr/bin/env python3
"""amenti ingest — take a raw generation and make it a repo asset.

    python3 ingest.py <file> <library-key> <card|terminal>

Does everything mechanical, in one step:

  1. CROP to the card slot ratio. Generations arrive at 9:16 (0.5625); the hero
     slot is 320x560 (0.5714). A 1.6% height trim, taken off the bottom so the
     crown is never touched.
  2. RESIZE to 1120 px tall — twice the hero's 560 px render height, ample for
     retina. Raw 2K files are four times more pixels than any display uses and
     three times the bytes.
  3. MEASURE saturation and compute the per-image grade factor that lands it on
     the deck's 0.105 at rest. Stored at FULL colour, graded in CSS, so the
     arrival pulse still reveals its true colour.
  4. NAME it {library-key}-{surface}.jpg. The library key is canonical; art
     resolves by convention and there is no map to keep in step.
  5. STAMP the provenance into the JPEG's EXIF and into img/MANIFEST.json.
  6. REWRITE img/grades.css so no HTML is ever edited to add a figure.

After this: git add, commit, push. Nothing else.
"""
import sys, os, json, datetime
import numpy as np
from PIL import Image
import provenance

TXT_LUM = 0.6383          # relative luminance of #c8e8d8, the terminal's body text
GND     = (3, 7, 5)       # .term-main composited over .term-shell over --ink
WCAG    = 4.5

SLOT   = 320 / 560
TALL   = 1120
TARGET = 0.105


def _lin(c):
    c /= 255.0
    return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4


def _rel(rgb):
    return 0.2126*_lin(rgb[0]) + 0.7152*_lin(rgb[1]) + 0.0722*_lin(rgb[2])


def term_opacity(path, margin=0.85):
    """Largest opacity this plate can sit behind terminal body text at.

    The terminal's own contrast is 15.4:1, so there is room — but the binding
    constraint is the plate's BRIGHT patches, not its mean. A single blown
    highlight under a line of type is what breaks legibility, so the test uses
    the 95th percentile as the worst case a line of text will land on.
    """
    a = np.asarray(Image.open(path).convert("L"), float)
    p95 = float(np.percentile(a, 95))
    lo, hi = 0.0, 1.0
    for _ in range(40):
        o = (lo + hi) / 2
        eff = [(1 - o) * g + o * p95 for g in GND]
        c = (max(TXT_LUM, _rel(eff)) + 0.05) / (min(TXT_LUM, _rel(eff)) + 0.05)
        if c >= WCAG: lo = o
        else: hi = o
    return round(lo * margin, 2)


def sat_of(im):
    a = np.asarray(im.convert("RGB"), float)
    return float(np.mean((a.max(2) - a.min(2)) / np.maximum(a.max(2), 1e-6)))


def grades():
    """Rewrite img/grades.css from the manifest. No hand-edited CSS, ever."""
    m = provenance.load()
    out = ["/* GENERATED BY ingest.py — do not edit.",
           "   One CSS multiplier per image. A single global value would SCALE",
           "   saturation, not EQUALISE it: at 0.32 a plate stored at 0.10 lands",
           "   at 0.03 while one stored at 0.31 lands at 0.10, and they stay",
           f"   three times apart. Each plate carries its own factor to {TARGET}. */"]
    for f, r in sorted(m["images"].items()):
        key, surf = r["key"], r["surface_slug"]
        if surf == "card":
            # the card plate appears in the roster tile and the codex slot.
            # The hero carousel is SVG puppets again and takes no grade.
            out.append(f'.rc-img[data-fig="{key}"],.nc-thumb[data-fig="{key}"],'
                       f'.mkt-thumb[data-fig="{key}"],'
                       f'.cdx-art[data-fig="{key}"][data-art-photo="card"]'
                       f'{{filter:saturate({r["art_sat"]});}}')
        else:
            # the codex detail shows the READING plate at 560px, so it takes
            # the terminal grade
            out.append(f'.cdx-art[data-fig="{key}"][data-art-photo="terminal"]'
                       f'{{filter:saturate({r["art_sat"]});}}')
            # THE TERMINAL — the largest canvas in the product. The terminal
            # plate sits behind the whole chat stream at the opacity computed
            # from its own bright patches, not a guessed constant.
            if r.get("pool_op"):
                # THE MOON KEY. The plate is no longer dimmed globally — it runs
                # near full strength and a MASK decides where the light falls.
                # --pool-x comes from the plate's own measured key_side, so the
                # CSS light agrees with the light already in the photograph
                # instead of arguing with it.
                out.append(
                    f'.term-main[data-fig="{key}"]::before{{'
                    f'background-image:url("img/{key}-terminal.jpg");'
                    f'opacity:{r["pool_op"]};'
                    f'--pool-x:{r["pool_x"]}%;'
                    f'filter:saturate({r["art_sat"]});}}')
    open("img/grades.css", "w").write("\n".join(out) + "\n")
    return len(m["images"])


def ingest(src, key, surface, note=""):
    assert surface in ("card", "terminal"), "surface must be card or terminal"
    im = Image.open(src).convert("RGB")
    W, H = im.size
    nh = int(round(W / SLOT))
    if nh <= H:
        im = im.crop((0, 0, W, nh))          # trim the bottom, protect the crown
    if im.height > TALL:
        im = im.resize((int(im.width * TALL / im.height), TALL), Image.LANCZOS)

    out = f"img/{key}-{surface}.jpg"
    im.save(out, quality=86, optimize=True, progressive=True)

    s = sat_of(Image.open(out))
    factor = round(min(TARGET / s, 1.0), 3) if s > 0 else 1.0

    m = provenance.load()
    rec = dict(file=os.path.basename(out), key=key,
               surface="hero/arena" if surface == "card" else "terminal",
               surface_slug=surface,
               grammar="presented" if surface == "card" else "absorbed",
               source=os.path.basename(src), note=note,
               model="flux.2-pro", service="OpenArt", aspect="9:16",
               resolution="2K", polish=True, seed=None,
               date=datetime.date.today().isoformat(),
               stored_saturation=round(s, 3), art_sat=factor,
               term_opacity=(term_opacity(out) if surface == "terminal" else None),
               colour_note="stored at full colour; graded in CSS via --art-sat")
    m["images"][os.path.basename(out)] = rec
    provenance.save(m)
    provenance.stamp(out, rec)
    n = grades()
    return out, im.size, s, factor, n


if __name__ == "__main__":
    if len(sys.argv) < 4:
        print(__doc__); sys.exit(1)
    src, key, surface = sys.argv[1:4]
    note = sys.argv[4] if len(sys.argv) > 4 else ""
    f, size, s, fac, n = ingest(src, key, surface, note)
    print(f"  wrote      {f}  {size[0]}x{size[1]}  {os.path.getsize(f)//1024} KB")
    print(f"  saturation {s:.3f} stored -> {s*fac:.3f} at rest (factor {fac})")
    print(f"  manifest   {n} images   grades.css rewritten")
    print(f"\n  SEED IS NULL. Put it in img/MANIFEST.json now, or it is gone.")
