#!/usr/bin/env node
/* ============================================================================
   probes/probe-hall.mjs  ·  THE HALL'S COUNTS
   ----------------------------------------------------------------------------
   Reads the registers and writes HALL-STATE.json: every number the hall is
   allowed to say, ~600 bytes, taken at the hour of writing.

     node probes/probe-hall.mjs            # write HALL-STATE.json
     node probes/probe-hall.mjs --check    # report only

   ── WHY A FILE AND NOT FIVE FETCHES AT QUERY TIME ─────────────────────────
   names.csv is 548 KB and PLATES.json is 127 KB. Counting them per question is
   seconds of latency for numbers that change weekly. This counts once; the
   hall reads ~600 bytes.

   ── EMPTY GLASS ───────────────────────────────────────────────────────────
   HALL.md holds the meaning and NO numbers. This file holds the numbers and
   no meaning. If a register cannot be read, its count is NULL and the hall
   says the count could not be read — it does not quote the last good number.
   A count that is silently stale is the fault this place was built to refuse.

   THIS WRITES NOTHING BUT HALL-STATE.json. It is a reading.
   ========================================================================== */

import fs from 'fs';
import path from 'path';

const ROOT  = process.argv.find(a => !a.startsWith('--') && a !== process.argv[0] && a !== process.argv[1]) || '.';
const OUT   = path.join(ROOT, 'HALL-STATE.json');
const CHECK = process.argv.includes('--check');

const say = m => console.log(m);
const failed = [];

function read(rel, asJson) {
  const p = path.join(ROOT, rel);
  try {
    const t = fs.readFileSync(p, 'utf8');
    return asJson ? JSON.parse(t) : t;
  } catch (e) {
    failed.push(rel + ' — ' + (e.code || e.message));
    return null;
  }
}

/* Every count individually guarded: one unreadable register nulls ITS counts,
   not the whole file. */
function count(fn) { try { const v = fn(); return Number.isFinite(v) ? v : null; } catch (e) { return null; } }

const roster = read('ROSTER-INDEX.json', true);
const keys   = read('img/KEYS.json', true);
const book   = read('PRODUCTION.json', true);
const spells = read('spec/spells.json', true);
const conf   = read('spell-conformance.json', true);
const schema = read('db/SCHEMA.json', true);
const srcs   = read('SOURCES.json', true);
const briefsSection = 'the briefs';

const state = {
  _: 'GENERATED by probes/probe-hall.mjs — do not edit. Every number the hall may state, read at the hour below. A null means the register could not be read THIS RUN; the hall says so rather than quoting a stale count.',
  generated: new Date().toISOString(),
  generator: 'probes/probe-hall.mjs',

  souls:            count(() => roster.totals.souls),
  souls_with_plates: count(() => roster.totals.withPlates),
  souls_with_rooms:  count(() => roster.totals.withRoom),
  keys:             count(() => keys.totals.keys),

  chapters_written: count(() => (book.chapters || []).filter(c => c.file).length),
  chapters_planned: count(() => (book.chapters || []).length),

  spells:            count(() => spells.spells.length),
  /* The conformance register carries its own totals and its field is `stamp`,
     not `state` — read 24 Aug after a guessed field name counted 0 of 8. Use
     the register's own arithmetic rather than redoing it wrong. */
  spells_confirmed:    count(() => conf.totals.confirmed),
  spells_contradicted: count(() => conf.totals.contradicted),
  spells_unproven:     count(() => conf.totals.unproven + conf.totals.unreachable),

  tables:            count(() => schema.counts.tables),
  functions:         count(() => schema.counts.functions),

  documents_indexed: count(() => srcs.counts.reachable),
  briefs: count(() => {
    let n = 0;
    for (const [g, items] of Object.entries(srcs.sources || {}))
      if (g.toLowerCase().startsWith(briefsSection)) n += items.length;
    return n || null;
  }),

  could_not_read: failed.length ? failed : undefined,
};

say('── the hall, counted ──────────────────────────────────────');
for (const [k, v] of Object.entries(state)) {
  if (k.startsWith('_') || k === 'generated' || k === 'generator' || k === 'could_not_read') continue;
  say('  ' + k.padEnd(18) + (v === null ? 'NULL — register unread' : v));
}
if (failed.length) { say(''); failed.forEach(f => say('  UNREAD  ' + f)); }

if (CHECK) {
  const nulls = Object.values(state).filter(v => v === null).length;
  say('\n--check: ' + (nulls ? nulls + ' count(s) unreadable' : 'every count read') + ', nothing written');
  process.exit(nulls ? 1 : 0);
}

fs.writeFileSync(OUT, JSON.stringify(state, null, 1) + '\n');
say('\nwrote         ' + OUT + '  (' + fs.statSync(OUT).size + ' bytes)');
say('───────────────────────────────────────────────────────────');
